package com.open.alpha2;

import android.content.Context;

/**
 * 英文語意配對引擎 - 和 SemanticMatcherZh (中文版) 屬於同一套「完全取代悠聊/
 * AlphaEnglishChat」的語意配對機制, 但這個 class 專門處理英文。
 *
 * 資料來源: assets/semantic/semantic_en.json, 3993 條英文問法/答案/動作記錄
 * (2026-09 起 v2 grouped 格式, 同中文版同一個 schema - 見 SemanticMatcherZh
 *  同 SemanticMatcherBase.load())。這份資料不是悠聊/AlphaEnglishChat 逐字拆出來
 *  或者翻譯來的 - 反編譯確認了
 * AlphaEnglishChat 主要靠 Api.ai (Dialogflow V1) 雲端 NLU, 而那個 API 已經在 2020 年
 * 3 月正式關閉, 英文語料沒得直接沿用。這 3993 句是跟著中文版 semantic_zh.json
 * 的結構和動作對照表 (operation/actionId/分類 pool 全部一致, 已驗證 202 動作清單裡面
 * 沒撞聲效), 用道地英文重新創作的問法/答案 - 詳見對話 history。
 *  2026-09 追加 EN+146 CHAT (en.mov/en.son/en.cit/en.arg: 電影 27／歌詞
 *  39／名言 40／潮語 40 組, 日常趣味問法＋5 個英文原生答案, 來自 en800.txt,
 *  已存在答案已剔除；id 避開原有 chat.### 命名)。2026-09 日常重建: 622 個舊
 *  CHAT (chat.001-476＋en.mov/son/cit/arg) 全刪, 新建 en.daily.001-200
 *  (每組地道英文 5 問法＋5 個答案: 001-040 問候天氣、041-080 飲食、081-120
 *  家庭家居寵物、121-160 工作學習健康、161-200 休閒旅行日常; 同法西日版一樣
 *  200 日常組動作全 __RANDOM__ (fallback 60 池，播嗰刻先 resolve)。85 ACTION＋13 FUNCTION (要求外的 beginconnect/connect/sleep 已刪)。
 *  每個 intent 內:
 *   q      - 用戶問法 (例如 "Dance for me", "How old are you")
 *   a      - 候選答案句 (5句, 隨機選一句做 TTS; 部分 FUNCTION 類沒答案句)
 *   type   - ACTION (有動作) | FUNCTION (系統操作, 例如音量/連線) | CHAT (日常對答, 動作 __RANDOM__)
 *   op     - operation 代號 (例如 "DANCE"), 和中文版一致, ACTION/FUNCTION 才有
 *   slot   - 方向/情緒等參數 (例如 "LEFT"), 只有部分 ACTION 有
 *   actionId - 已經由 operation+slot 對應好的、202 動作清單裡面的真實 action id
 *              (也就是 xiaozhi_actions.json 那 202 個裡面其中一個), 只有 ACTION 才有。
  *              兩種特殊值: "__RANDOM__" (TFBOY 這類沒固定動作, 隨機 filler 池 60 個裡面隨便選一個
 *              - 見 resolveRandomActionId()); "__RANDOM_CATEGORY__<key>" (2026-08 新增
 *              - 用戶說到分類名但沒說出具體哪個動作, 例如 "Dance for me" "Do some yoga",
 *              要在那個分類裡面隨機選一個 - 見 resolveCategoryRandomActionId())
 *
 * 分類 random (__RANDOM_CATEGORY__): 和中文版共用同一份
 * assets/semantic/action_category_pools.json (17 個分類；注意池入面有有聲效
 * 動作（例如成個 DANCE_ANY 都有音樂），有聲判斷唔喺呢度做——SemanticCenter
 * 播之前 resolve 做真實 id 再查 ActionDirect.isSoundAction()，有聲就禁 TTS),
 * 三層 fallback: 具體動作名 (原有 32 operation) > 子分類 (例如 DANCE_KIDS) > 大分類
 * (例如 DANCE_ANY)。
 *
 * 這個 class 只負責「文字 -> 配對結果」, 不負責執行 TTS/動作 - 跟著這個 project
 * 一貫的分層方式 (就像 resolveActionId() 只負責解析、不負責 call
 * robot.action_PlayActionName() 那樣), 執行那一步留給呼叫方 (SemanticCenter 的
 * handleSemanticMatch) 做, 方便測試和重用。
 *
 * 只做英文 - 和 SemanticMatcherZh (中文版) 各自獨立, 沒在這個 class 裡加
 * language 參數 (因為機身 ASR 引擎本身一次只能選到一種語言, 兩個 matcher 不會同時用)。
 * SemanticCenter.handleSemanticMatch() 根據對話語言／文字判斷結果, 選用哪一個。
 * 載入/比對/分類 random 的實際邏輯 (和中文版逐字相同) 全部在
 * SemanticMatcherBase, 這裡只提供英文專屬的 TAG/assets 路徑/fallback 問法組
 * (2026-09 抽出共用 base 前, 這個 class 和 SemanticMatcherZh 是兩份幾乎逐字
 * 重複的完整實作; MatchResult 現在也是共用同一個型別, SemanticCenter 不用再
 * toZhResult() 手動轉接)。
 *
 * Zero-third-party-dependency: 只用 org.json (Android 內建, 經 base class), 沒額外
 * library。
 *
 * 命名備註: 2026-09 之前這個 class 叫 IflytekSemanticMatcherEn - 個名純粹歷史原因
 * (中文版問法資料最初由 iFlytek APK 反編譯還原, 英文版跟同一套結構), 同機身已經
 * 永久不再用的 Nuance/iFlytek binder TTS/ASR 引擎完全沒有關係, 僅個名容易誤導。
 * 改名為 SemanticMatcherEn 消除這個誤導 (功能行為完全不變)。
 */
public class SemanticMatcherEn extends SemanticMatcherBase {
    private static final String TAG = "SemanticMatcherEn";
    private static final String ASSET_PATH = "semantic/semantic_en.json";

    /** fallback 答句池 - en800.txt 用剩的未配對句全數搬過嚟 (generated, 唔好手改；
     *  要加減句請改 english_raw_lines.json + semantic_en.json 配對結果再 rerun；
     *  粗口/槍/性/復仇威脅句已剔除，唔入池)。
     *  聽唔明就隨機噏一句，動作全部 __RANDOM__ (SemanticCenter 見到會即場由隨機
     *  filler 池 60 個裡面選一個)，次次唔同 - 同中日西法版的 fallback 做法一致。 */
    private static final String[] FALLBACK_QUESTIONS = {
            "I'm gonna make him an offer he can't refuse.",
            "May the Force be with you.",
            "Go ahead, make my day.",
            "You talkin' to me?",
            "Fasten your seatbelts. It's going to be a bumpy night.",
            "I'm the king of the world!",
            "Carpe diem. Seize the day, boys. Make your lives extraordinary.",
            "Elementary, my dear Watson.",
            "It's alive! It's alive!",
            "Houston, we have a problem.",
            "You can't handle the truth!",
            "I'll be back.",
            "Here's Johnny!",
            "They're here!",
            "Bond. James Bond.",
            "Why so serious?",
            "Keep your friends close, but your enemies closer.",
            "Hasta la vista, baby.",
            "My precious.",
            "I see dead people.",
            "Nobody puts Baby in a corner.",
            "I'm walking here! I'm walking here!",
            "To me, you are perfect.",
            "I wish I knew how to quit you.",
            "I'm also just a girl, standing in front of a boy, asking him to love her.",
            "You complete me.",
            "It doesn't matter who you are on the outside, the main thing is who you are on the inside.",
            "You should be kissed and often, and by someone who knows how.",
            "So how do you drop a quick four grand?",
            "Death cannot stop true love. All it can do is delay it for a while.",
            "You make me want to be a better man.",
            "I would rather spend one lifetime with you, than face all the Ages of this world alone.",
            "They say when you meet the love of your life, time stops, and that's true.",
            "I love you. I knew it the minute I met you.",
            "We accept the love we think we deserve.",
            "No matter what happens to us, every day with you is the best day of my life.",
            "I think I'd miss you even if we'd never met.",
            "In my opinion, the best thing you can do is find a person who loves you for exactly what you are.",
            "I would have preferred one breath of her hair, one kiss of her mouth, one touch of her hand, than eternity without it.",
            "You will never age for me, nor fade, nor die.",
            "Life is not the amount of breaths you take, it's the moments that take your breath away.",
            "Don't let anyone ever make you feel like you don't deserve what you want.",
            "It's only after we've lost everything that we're free to do anything.",
            "Get busy living, or get busy dying.",
            "Great men are not born great, they grow great.",
            "All we have to decide is what to do with the time that is given us.",
            "Oh yes, the past can hurt. But from the way I see it, you can either run from it, or learn from it.",
            "Do, or do not. There is no try.",
            "Why do we fall, Bruce? So we can learn to pick ourselves up.",
            "It is not our abilities that show what we truly are… it is our choices.",
            "If you want something, go get it. Period.",
            "The flower that blooms in adversity is the most rare and beautiful of all.",
            "Real loss is only possible when you love something more than you love yourself.",
            "I am Iron Man.",
            "Avengers, assemble!",
            "With great power comes great responsibility.",
            "I have a bad feeling about this.",
            "I am Groot.",
            "Wakanda Forever!",
            "You either die a hero, or you live long enough to see yourself become the villain.",
            "I'm not bad. I'm just drawn that way.",
            "Life finds a way.",
            "Freedom!",
            "They may take our lives, but they'll never take our freedom!",
            "Are you not entertained?",
            "Gentlemen, you can't fight in here! This is the War Room!",
            "In space, no one can hear you scream.",
            "The needs of the many outweigh the needs of the few.",
            "Live long and prosper.",
            "I am your density.",
            "I am the danger!",
            "I'm not trapped in here with you. You're trapped in here with me!",
            "Whatever doesn't kill you, simply makes you stranger.",
            "If you're good at something, never do it for free.",
            "I'm a survivor!",
            "Do not go gentle into that good night.",
            "Love is the one thing that transcends time and space.",
            "The first rule of Fight Club is: You do not talk about Fight Club.",
            "What we've got here is failure to communicate.",
            "I love the smell of napalm in the morning.",
            "I am serious... and don't call me Shirley.",
            "Greed, for lack of a better word, is good.",
            "Sell me this pen.",
            "Fun fact: I'm a billionaire.",
            "I'm not crazy, my mother had me tested.",
            "On Wednesdays we wear pink.",
            "That's so fetch!",
            "You can't sit with us!",
            "Hold onto your butts.",
            "Look at me. I'm the captain now.",
            "Bye, Felicia.",
            "Inconceivable!",
            "You keep using that word. I do not think it means what you think it means.",
            "That escalated quickly.",
            "I'm kind of a big deal.",
            "Schwing!",
            "So you're telling me there's a chance?",
            "I'm a peacock, you gotta let me fly!",
            "Did we just become best friends?",
            "I'm in a glass cage of emotion!",
            "Show me.",
            "Nobody's perfect.",
            "Fasten your seatbelts, it's going to be a bumpy ride.",
            "Is it safe?",
            "One does not simply walk into Mordor.",
            "You shall not pass!",
            "What's in the box?!",
            "Just keep swimming.",
            "Not everyone can become a great artist, but a great artist can come from anywhere.",
            "The only thing predictable about life is its unpredictability.",
            "Let it go, let it go!",
            "The real death is that no one in the world remembers you.",
            "When life gets you down, you know what you gotta do? Just keep swimming.",
            "I don't want to survive. I want to live.",
            "If you build it, he will come.",
            "There's no crying in baseball!",
            "I am the master of my fate, I am the captain of my soul.",
            "Every man dies, not every man really lives.",
            "I'm not a smart man, but I know what love is.",
            "Stupid is as stupid does.",
            "Run, Forrest, run!",
            "Death is just another path, one that we all must take.",
            "I have a very particular set of skills.",
            "Whatever you are, be a good one.",
            "Manners maketh man.",
            "There is no poisonous snakes, only poisonous thoughts.",
            "Your story may not have such a happy beginning, but that doesn't make you who you are.",
            "It's the rest of your story. Who do you choose to be?",
            "To die would be an awfully big adventure.",
            "Sometimes the right path is not the easiest one.",
            "Venture outside your comfort zone. The rewards are worth it.",
            "You controls your destiny—you don't need magic to do it.",
            "The only limits for tomorrow are the doubts we have today.",
            "Keep moving forward.",
            "Always.",
            "After all this time? Always.",
            "Mischief managed.",
            "I solemnly swear that I am up to no good.",
            "Look at the stars. The great kings of the past look down on us from those stars.",
            "And in that moment, I swear we were infinite.",
            "The only true wisdom is in knowing you know nothing.",
            "An unexamined life is not worth living.",
            "Happiness depends upon ourselves.",
            "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
            "He who has a why to live can bear almost any how.",
            "That which does not kill us makes us stronger.",
            "I think, therefore I am.",
            "Life must be understood backward. But it must be lived forward.",
            "The only thing I know is that I know nothing.",
            "Be the change that you wish to see in the world.",
            "Live as if you were to die tomorrow. Learn as if you were to live forever.",
            "An eye for an eye only ends up making the whole world blind.",
            "In three words I can sum up everything I've learned about life: it goes on.",
            "Life is what happens when you're busy making other plans.",
            "Turn your wounds into wisdom.",
            "Life is 10% what happens to you and 90% how you react to it.",
            "Get busy living or get busy dying.",
            "You only live once, but if you do it right, once is enough.",
            "In the end, it's not the years in your life that count. It's the life in your years.",
            "The unexamined life is not worth living.",
            "Do not go where the path may lead, go instead where there is no path and leave a trail.",
            "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
            "It is during our darkest moments that we must focus to see the light.",
            "The mind is everything. What you think you become.",
            "Peace comes from within. Do not seek it without.",
            "Knowledge speaks, but wisdom listens.",
            "Everything has beauty, but not everyone sees it.",
            "Simplicity is the ultimate sophistication.",
            "Where there is love there is life.",
            "The only limit to our realization of tomorrow will be our doubts of today.",
            "Money and success don't change people; they merely amplify what is already there.",
            "It is never too late to be what you might have been.",
            "There is no charm equal to tenderness of heart.",
            "To love oneself is the beginning of a lifelong romance.",
            "Imagination is more important than knowledge.",
            "Try not to become a man of success, but rather try to become a man of value.",
            "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
            "If I have seen further it is by standing on the shoulders of Giants.",
            "Nothing in life is to be feared, it is only to be understood.",
            "Be less curious about people and more curious about ideas.",
            "Intelligence is the ability to adapt to change.",
            "Look up at the stars and not down at your feet.",
            "However difficult life may seem, there is always something you can do and succeed at.",
            "Science is a way of thinking much more than it is a body of knowledge.",
            "Somewhere, something incredible is waiting to be known.",
            "The good thing about science is that it's true whether or not you believe in it.",
            "Genius is one percent inspiration and ninety-nine percent perspiration.",
            "I have not failed. I've just found 10,000 ways that won't work.",
            "The present is theirs; the future, for which I really worked, is mine.",
            "If you want to find the secrets of the universe, think in terms of energy, frequency and vibration.",
            "Innovation distinguishes between a leader and a follower.",
            "The people who are crazy enough to think they can change the world are the ones who do.",
            "When something is important enough, you do it even if the odds are not in your favor.",
            "Persistence is very important. You should not give up unless you are forced to give up.",
            "Move fast and break things. Unless you are breaking stuff, you are not moving fast enough.",
            "The biggest risk is not taking any risk.",
            "If you double the number of experiments you do per year you're going to double your inventiveness.",
            "Your brand is what other people say about you when you're not in the room.",
            "It's fine to celebrate success, but it is more important to heed the lessons of failure.",
            "Content is king.",
            "Technology is just a tool. In terms of getting the kids working together and motivating them, the teacher is the most important.",
            "The measure of intelligence is the ability to change.",
            "Logic will get you from A to Z; imagination will get you everywhere.",
            "An investment in knowledge pays the best interest.",
            "Equipped with his five senses, man explores the universe around him and calls the adventure Science.",
            "Astronomy compels the soul to look upwards and leads us from this world to another.",
            "We build too many walls and not enough bridges.",
            "Simplicity is the prerequisite for reliability.",
            "Success is not final, failure is not fatal: it is the courage to continue that counts.",
            "If you're going through hell, keep going.",
            "Attitude is a little thing that makes a big difference.",
            "The price of greatness is responsibility.",
            "Never, never, never give up.",
            "In the middle of difficulty lies opportunity.",
            "It always seems impossible until it's done.",
            "The greatest glory in living lies not in never falling, but in rising every time we fall.",
            "Do one thing every day that scares you.",
            "No one can make you feel inferior without your consent.",
            "The future belongs to those who believe in the beauty of their dreams.",
            "Ask not what your country can do for you — ask what you can do for your country.",
            "Change is the law of life. And those who look only to the past or present are certain to miss the future.",
            "I have a dream.",
            "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
            "The time is always right to do what is right.",
            "Our lives begin to end the day we become silent about things that matter.",
            "Believe you can and you're halfway there.",
            "Do what you can, with what you have, where you are.",
            "Keep your eyes on the stars, and your feet on the ground.",
            "Courage is grace under pressure.",
            "A man can be destroyed but not defeated.",
            "The way to get started is to quit talking and begin doing.",
            "All our dreams can come true, if we have the courage to pursue them.",
            "If you can dream it, you can do it.",
            "I've failed over and over and over again in my life. And that is why I succeed.",
            "Some people want it to happen, some wish it would happen, others make it happen.",
            "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
            "Courage is resistance to fear, mastery of fear — not absence of fear.",
            "Action is the foundational key to all success.",
            "Everything you can imagine is real.",
            "Opportunity is missed by most people because it is dressed in overalls and looks like work.",
            "Hardships often prepare ordinary people for an extraordinary destiny.",
            "A leader is one who knows the way, goes the way, and shows the way.",
            "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
            "To be, or not to be, that is the question.",
            "Love all, trust a few, do wrong to none.",
            "The course of true love never did run smooth.",
            "We are such stuff as dreams are made on.",
            "If you tell the truth, you don't have to remember anything.",
            "Always forgive your enemies; nothing annoys them so much.",
            "We are all in the gutter, but some of us are looking at the stars.",
            "Be yourself; everyone else is already taken.",
            "A joke is a very serious thing.",
            "Words are, in my not-so-humble opinion, our most inexhaustible source of magic.",
            "It is our choices, Harry, that show what we truly are, far more than our abilities.",
            "Rock bottom became the solid foundation on which I rebuilt my life.",
            "Real courage is when you know you're licked before you begin, but you begin anyway and see it through no matter what.",
            "I words cannot express how much I love you.",
            "There is no agony like bearing an untold story inside you.",
            "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
            "You can't use up creativity. The more you use, the more you have.",
            "Every child is an artist. The problem is how to remain an artist once he grows up.",
            "I dream my painting and I paint my dream.",
            "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.",
            "Great things are done by a series of small things brought together.",
            "To create is to live twice.",
            "Freedom is nothing but a chance to be better.",
            "Doubt is the origin of wisdom.",
            "The place to improve the world is first and foremost in one's own heart and head and hands.",
            "Brevity is the soul of wit.",
            "Risk comes from not knowing what you're doing.",
            "It takes 20 years to build a reputation and five minutes to ruin it.",
            "Be fearful when others are greedy and greedy when others are fearful.",
            "In the business world, the rearview mirror is always clearer than the windshield.",
            "The most important investment you can make is in yourself.",
            "If you don't find a way to make money while you sleep, you will work until you die.",
            "Success is getting what you want, happiness is wanting what you get.",
            "If you judge people, you have no time to love them.",
            "Peace begins with a smile.",
            "Not all of us can do great things. But we can do small things with great love.",
            "Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin.",
            "Real power is not about control, but about impact.",
            "When they go low, we go high.",
            "There is no limit to what we, as women, can accomplish.",
            "Yes we can.",
            "The future rewards those who press on. I don't have time to feel sorry for myself.",
            "Don't compromise yourself. You're all you've got.",
            "Life shrinks or expands in proportion to one's courage.",
            "Happiness is not something ready made. It comes from your own actions.",
            "If you think you are too small to make a difference, try sleeping with a mosquito.",
            "Success usually comes to those who are too busy to be looking for it.",
            "Go confidently in the direction of your dreams! Live the life you've imagined.",
            "Things do not change; we change.",
            "Whatever you do, do it well.",
            "I attribute my success to this: I never gave or took any excuse.",
            "You miss 100% of the shots you don't take.",
            "Defeat is not bitter unless you swallow it.",
            "Failure is the opportunity to begin again more intelligently.",
            "Whether you think you can, or you think you can't — you're right.",
            "Quality means doing it right when no one is looking.",
            "I will survive.",
            "Don't stop believin'.",
            "What doesn't kill you makes you stronger.",
            "It's my life, it's now or never.",
            "I'm on the right track, baby, I was born this way.",
            "Every new beginning comes from some other beginning's end.",
            "Work it, make it, do it, makes us harder, better, faster, stronger.",
            "You can't always get what you want, but if you try sometimes, you find you get what you need.",
            "You're beautiful, no matter what they say.",
            "I am the master of my sea.",
            "Even the darkest night will end and the sun will rise.",
            "I won't give up, no I won't give in.",
            "Shine bright like a diamond.",
            "Who runs the world? Girls.",
            "Nothing is impossible, the word itself says 'I'm possible'!",
            "Freedom's just another word for nothing left to lose.",
            "I came in like a wrecking ball.",
            "The sky's the limit.",
            "Turn your magic on.",
            "I believe I can fly, I believe I can touch the sky.",
            "High hopes, high hopes.",
            "There's a light that never goes out.",
            "Keep your head up, keep your heart strong.",
            "Pick yourself up, dust yourself off, start all over again.",
            "Break free from the chains that bind you.",
            "All of me loves all of you.",
            "Just the way you are.",
            "I will always love you.",
            "Every breath you take, I'll be watching you.",
            "You are the best thing that's ever been mine.",
            "Can't help falling in love with you.",
            "God gave me you for the ups and downs.",
            "You're the one that I want.",
            "I can't live without you.",
            "Take my hand, take my whole life too.",
            "Cause baby, you're a firework.",
            "Love is all you need.",
            "You're the first, my last, my everything.",
            "I don't wanna miss a thing.",
            "I have loved you for a thousand years.",
            "You make me feel like a natural woman.",
            "Endless love.",
            "Thinking out loud.",
            "Love me like you do.",
            "My heart will go on.",
            "You belong with me.",
            "Unbreak my heart.",
            "I knew I loved you before I met you.",
            "Heaven is a place on earth with you.",
            "Hold my hand and don't let go.",
            "Crazy in love.",
            "You make my dreams come true.",
            "When I look into your eyes, I see a light.",
            "Love story.",
            "In your eyes, I see the future.",
            "Sweet disposition.",
            "Bleeding love.",
            "Say you won't let go.",
            "Your love is my drug.",
            "Someone like you.",
            "Yesterday, all my troubles seemed so far away.",
            "Hurt.",
            "Nothing compares 2 U.",
            "Careless whisper.",
            "When the party's over.",
            "The scientist.",
            "Losing my religion.",
            "Creep.",
            "Wish you were here.",
            "Boulevard of broken dreams.",
            "Lucid dreams.",
            "Stitches.",
            "Back to black.",
            "All by myself.",
            "Smells like teen spirit.",
            "Break my heart.",
            "Let her go.",
            "Say something, I'm giving up on you.",
            "Skinny love.",
            "Chandelier.",
            "I leave a light on.",
            "Torn.",
            "Shadow of the day.",
            "In the end, it doesn't even matter.",
            "When you're gone.",
            "Dance monkey.",
            "Wild thoughts.",
            "Levitating.",
            "Shape of you.",
            "Starboy.",
            "Despacito.",
            "Good 4 u.",
            "Dynamite.",
            "Radioactive.",
            "Counting stars.",
            "Youth.",
            "Smells like freedom.",
            "Like a rolling stone.",
            "Stairway to heaven.",
            "Bohemian rhapsody.",
            "Wonderwall.",
            "Sweet caroline.",
            "Dancing queen.",
            "Thriller.",
            "Smooth criminal.",
            "Imagine all the people living life in peace.",
            "Man in the mirror.",
            "Heal the world, make it a better place.",
            "Where is the love?",
            "Change the world.",
            "We are the world.",
            "Space oddity.",
            "Heroes.",
            "Bridge over troubled water.",
            "Stand by me.",
            "R-E-S-P-E-C-T.",
            "Superstition.",
            "Fast car, slow life.",
            "Redemption song.",
            "Karma police.",
            "Zombie.",
            "Mad world.",
            "Comfortably numb.",
            "Losing my mind.",
            "Fly me to the moon.",
            "My way.",
            "Unforgettable.",
            "At last.",
            "Georgia on my mind.",
            "Hallelujah.",
            "To the moon and back.",
            "End of the road.",
            "No cap.",
            "She has immaculate vibes.",
            "He's got unspoken Rizz.",
            "Main character energy.",
            "Spill the tea.",
            "It's giving vintage.",
            "Left no crumbs.",
            "Periodt.",
            "Living rent-free in my head.",
            "I'm dead.",
            "That's a major red flag.",
            "Green flag behavior.",
            "Caught in 4K.",
            "Flexing on the 'Gram.",
            "Side eye.",
            "Era.",
            "Ghosting someone.",
            "Soft launch.",
            "Hard launch.",
            "Situationship.",
            "Breadcrumbing.",
            "I'm weak.",
            "Touch grass.",
            "It's a flex.",
            "Don't be a hater.",
            "High key.",
            "Low key.",
            "Slay all day.",
            "Clout chasing.",
            "Aesthetic on point.",
            "Cancel culture.",
            "Vibe check.",
            "Bet.",
            "Say less.",
            "For real though.",
            "I can't even.",
            "Big yikes.",
            "It hits different.",
            "Salty much?",
            "Savage!",
            "That's sus.",
            "Don't be basic.",
            "Felt that.",
            "Valid.",
            "It is what it is.",
            "Real ones know.",
            "No flex, but...",
            "I'm down.",
            "I'm out.",
            "Keep it 100.",
            "My bad.",
            "No worries.",
            "Same difference.",
            "Deadass?",
            "Don't sleep on this.",
            "Straight facts.",
            "I'm shook.",
            "Hits the spot.",
            "Bummer!",
            "Not gonna lie.",
            "To be fair.",
            "I'm screaming.",
            "Cringe.",
            "Catch feelings.",
            "Good call.",
            "Out of pocket.",
            "Bite the bullet.",
            "Hustle culture.",
            "Brain dump.",
            "Burnout is real.",
            "Game changer.",
            "Work hard, play hard.",
            "Think outside the box.",
            "Low-hanging fruit.",
            "Pivoting.",
            "Bite-sized information.",
            "Soft skills matter.",
            "Proactive mindset.",
            "Bandwidth.",
            "Level up.",
            "Deep work.",
            "Digital nomad.",
            "Multitasking mode.",
            "Hit the ground running.",
            "Set boundaries.",
            "Work smart, not hard.",
            "Out of the loop.",
            "In the loop.",
            "Empower yourself.",
            "Win-win situation.",
            "Fast-track.",
            "Keep momentum.",
            "Zero to one.",
            "Feedback loop.",
            "Core memory unlocked.",
            "Stay in your lane.",
            "It's lit!",
            "Turn up!",
            "Party animal.",
            "FOMO.",
            "JOMO.",
            "Snacked.",
            "Serving looks.",
            "Dressed to impress.",
            "Sip and paint.",
            "Main stage vibes.",
            "Good vibes only.",
            "Glow in the dark.",
            "Mic drop.",
            "Pop off!",
            "Go hard or go home.",
            "Bucket list item.",
            "Chill vibes.",
            "Behind the scenes.",
            "Sneak peek.",
            "Trendsetter.",
            "Influencer status.",
            "Viral hit.",
            "One-hit wonder.",
            "Manifesting it.",
            "Protect your peace.",
            "Trust the process.",
            "Everything happens for a reason.",
            "Embrace the chaos.",
            "Self-love first.",
            "Grounded and focused.",
            "Mindfulness moment.",
            "Energy vampires.",
            "Unapologetically me.",
            "Growth mindset.",
            "Overthinking mode.",
            "Imposter syndrome.",
            "Comfort zone.",
            "Break boundaries.",
            "Inner peace.",
            "Positive reinforcement.",
            "Emotional maturity.",
            "Let go of expectations.",
            "Be present.",
            "Radiate positivity.",
            "Stay humble, hustle hard.",
            "Find your spark.",
            "Choose joy.",
            "Kindness is free.",
            "Quality over quantity.",
            "Less is more.",
            "Stay true to yourself.",
            "Silver lining.",
            "Blessing in disguise.",
            "Count your blessings.",
            "Day one or day ninety-nine.",
            "Make it count.",
            "Own your story.",
            "Unstoppable force.",
            "Breathe in, breathe out.",
            "Hope fuels action.",
            "The best is yet to come.",
    };

    public SemanticMatcherEn(Context context) {
        super(context, TAG, ASSET_PATH, FALLBACK_QUESTIONS, randomActions());
    }

    /** fallback 動作全部 __RANDOM__：幾多答句就幾多個位，SemanticCenter
     *  見到呢個標記會即場隨機選動作 (見 ActionDirect.resolveRandomActionId())。 */
    private static String[] randomActions() {
        String[] a = new String[FALLBACK_QUESTIONS.length];
        for (int i = 0; i < a.length; i++) {
            a[i] = "__RANDOM__";
        }
        return a;
    }
}

