package com.open.alpha2;

import android.content.Context;

/**
 * 葡萄牙文語意配對引擎 - 和 SemanticMatcherZh (中文版)／SemanticMatcherEn
 * (英文版)／SemanticMatcherEs (西班牙文版)／SemanticMatcherFr (法文版)／
 * SemanticMatcherJa (日文版) 同一套語意配對機制, 專門處理葡萄牙文。
 *
 * 骨架：assets/semantic/semantic_pt.json 目前有 85 ACTION (id/op/slot/actionId
 * 全同英文版；每組葡文 5 問法＋5 答案，巴西口語) ＋200 日常 CHAT
 * (pt.daily.001-200，每組 5 問法＋5 答案：001-040 問候天氣、041-080 飲食、
 * 081-120 家庭家居寵物、121-160 工作學習健康、161-200 休閒旅行日常；
 * 動作全 __RANDOM__)。
 * pt800（電影／歌詞／名言／潮語各 200）啱意境的已按意配入日常組答案
 * （每組最多加 3 句）；8 句暴力／粗口／色情剔除唔用；
 * 剩低 562 句全入下面 fallback，動作全 __RANDOM__（60 池）。
 *
 * 這個 class 只負責「文字 -> 配對結果」, 不負責執行 TTS/動作 - 跟著這個 project
 * 一貫的分層方式，執行那一步留給呼叫方 (SemanticCenter 的 handleSemanticMatch)
 * 做, 方便測試和重用。
 *
 * 只做葡萄牙文 - 和其他語言版各自獨立, 沒在這個 class 裡加 language 參數
 * (因為機身 ASR 引擎本身一次只能選到一種語言, matcher 不會同時用）。
 * SemanticCenter.handleSemanticMatch() 根據對話語言／文字判斷結果, 選用哪一個。
 * 載入/比對/分類 random 的實際邏輯全部在 SemanticMatcherBase, 這裡只提供
 * 葡萄牙文專屬的 TAG/assets 路徑/fallback 問法組。
 *
 * Zero-third-party-dependency: 只用 org.json (Android 內建, 經 base class), 沒額外
 * library。
 */
public class SemanticMatcherPt extends SemanticMatcherBase {
    private static final String TAG = "SemanticMatcherPt";
    private static final String ASSET_PATH = "semantic/semantic_pt.json";

    /** 骨架：fallback 空池（內容後加；base.fallback() 空池回 null，唔 crash）。 */
    private static final String[] FALLBACK_QUESTIONS = {
            "Cidade de Deus nunca esteve tão longe do céu.",
            "A favela não é de ninguém, é de quem domina.",
            "No morro, se você vacilar, você roda.",
            "Nunca serão! Jamais serão!",
            "Não vai subir ninguém!",
            "O inimigo agora é outro.",
            "O homem é o lobo do homem.",
            "Ninguém sai impune de uma guerra.",
            "Quem tem boca vai a Roma, quem tem arma vai a qualquer lugar.",
            "O destino não tolera fracos.",
            "Acabou o amor, isso aqui é uma guerra.",
            "Eu só queria poder ver o seu rosto.",
            "Você muda tudo sem nem perceber.",
            "Quero ser independente, mas quero você do meu lado.",
            "Às vezes, o amor está onde a gente menos espera.",
            "Eu amo você não pelo que você é, mas pelo que eu sou quando estou com você.",
            "O coração tem razões que a própria razão desconhece.",
            "Você é a minha pessoa favorita no mundo inteiro.",
            "Mesmo longe, eu sinto você perto de mim.",
            "Prometa que não vai se esquecer de mim.",
            "Nossos caminhos se cruzaram por um motivo.",
            "Você mudou minha vida para sempre.",
            "Sem você, a vida é apenas um cenário sem cor.",
            "Amar é ter a coragem de ser vulnerável.",
            "O tempo para quando estou com você.",
            "Você é o meu começo, meio e fim.",
            "Nenhum oceano pode nos separar.",
            "Te amar foi a decisão mais fácil que já tomei.",
            "O destino sabia o que estava fazendo quando nos aproximou.",
            "Sua voz é a minha música favorita.",
            "Eu procuraria você em mil vidas.",
            "O amor verdadeiro nunca morre, ele apenas se transforma.",
            "Você é o meu porto seguro.",
            "A vida é curta demais para não dizer 'eu te amo'.",
            "Quando eu olhei nos seus olhos, eu soube.",
            "Você completa as partes que faltavam em mim.",
            "Eu escolheria você todas as vezes.",
            "Sua felicidade é a minha felicidade.",
            "Não existem coincidências no amor.",
            "Eu nunca pensei que pudesse amar alguém assim.",
            "Seja o amor da sua própria vida primeiro.",
            "O que Deus uniu, o homem não separa.",
            "Sua ausência é um vazio que nada preenche.",
            "Sempre foi você, desde o primeiro momento.",
            "A vida me deu você de presente.",
            "Tudo fica melhor quando você está por perto.",
            "Ame agora, porque o amanhã é uma incerteza.",
            "Eu te amo mais do que as palavras podem dizer.",
            "Cumade Nossa Senhora, valei-me nessa hora!",
            "Eu sou um homem de palavra... pena que a palavra é fraca!",
            "Deus é bom, mas o Diabo não é bobo.",
            "Dinheiro na mão é vendaval!",
            "O diabo que te carregue!",
            "Você não é todo mundo!",
            "A vida não é um morango, meu bem.",
            "Deus escreve certo por linhas tortas.",
            "Tudo passa, até a uva passa.",
            "Há males que vêm para o bem.",
            "Santo de casa não faz milagre.",
            "O hábito não faz o monge.",
            "Quem ri por último, ri melhor.",
            "Os seus problemas você deve esquecer... Isso é viver, é aprender: Hakuna Matata!",
            "Ohana quer dizer família. Família quer dizer nunca abandonar ou esquecer.",
            "Eu sou o rei do mundo!",
            "Aqui está olhando para você, garota.",
            "Eu vejo pessoas mortas.",
            "Hakuna Matata significa sem problemas.",
            "Mostre-me o dinheiro!",
            "Procurarei você, encontrarei você e matarei você.",
            "Mantenha os seus olhos abertos.",
            "A verdade está lá fora.",
            "Siga o coelho branco.",
            "Eu sou inevitável.",
            "Não existe colher.",
            "Você é mais forte do que parece, e mais inteligente do que pensa.",
            "O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.",
            "Não deixe ninguém dizer que você não pode fazer algo.",
            "Tudo vale a pena se a alma não é pequena.",
            "Tenho em mim todos os sonhos do mundo.",
            "Navegar é preciso; viver não é preciso.",
            "O poetas é um fingidor. Finge tão completamente que chega a fingir que é dor a dor que deveras sente.",
            "Para ser grande, sê inteiro: nada teu exagera ou exclui.",
            "Sentir tudo de todas as maneiras.",
            "O valor das coisas não está no tempo que elas duram, mas na intensidade com que acontecem.",
            "Não sou nada. Nunca serei nada. Não posso querer ser nada. À parte isso, tenho em mim todos os sonhos do mundo.",
            "Só uma coisa torna um sonho impossível: o medo de falhar.",
            "Não te esqueças: o teu coração está onde está o teu tesouro.",
            "Esperar dói. Esquecer dói. Mas não saber que decisão tomar é o pior dos sofrimentos.",
            "Não tente ser útil. Tente ser você mesmo: isso basta, e isso faz toda a diferença.",
            "O segredo da vida é cair sete vezes e levantar oito.",
            "Quantas coisas perdemos por medo de perder.",
            "Ninguém pode julgar os outros, porque cada um sabe da sua própria dor.",
            "O amor não precisa de explicações; ele precisa de manifestação.",
            "Somos todos cego que podem ver, mas não veem.",
            "A sabedoria não está em não errar, mas em saber corrigir os erros.",
            "Dentro de nós há algo que não tem nome, essa coisa é o que somos.",
            "Os homens são como os livros: o exterior pode ser bonito, mas o importante é o conteúdo.",
            "Aprendi a não tentar convencer ninguém. A tarefa de convencer é uma falta de respeito.",
            "O destino não é uma questão de sorte, é uma questão de escolha.",
            "O passado já não existe, o futuro é uma incerteza, o presente é tudo o que temos.",
            "A arte de viver consiste em tirar o maior bem do pior mal.",
            "Esquecer é uma necessidade. A vida é uma lavagem da memória.",
            "Cada qual sabe o peso da sua cruz.",
            "O tempo é um invisível tecelão.",
            "Lágrimas não lavam dores, mas aliviam a alma.",
            "O riso é o tempero da vida.",
            "Renda-se, como eu me rendi. Mergulhe no que você não conhece.",
            "Liberdade é pouco. O que eu quero ainda não tem nome.",
            "Até cortar os próprios defeitos pode ser perigoso.",
            "O futuro nos pertence a partir do momento em que o criamos.",
            "A esperança é um empréstimo feito à felicidade.",
            "Viver é a coisa mais rara do mundo. A maioria das pessoas apenas existe.",
            "A coragem é a primeira das qualidades humanas, porque é a qualidade que garante todas as outras.",
            "Pensar é agir sobre o pensamento.",
            "Amar é inventar o outro no espelho da própria alma.",
            "A sabedoria começa na dúvida.",
            "O teu amor torna-me forte, o teu ódio torna-me imparável.",
            "Eu não busco os recordes, os recordes é que me buscam a mim.",
            "Sem trabalho duro, o talento não é nada.",
            "Se você acha que já é perfeito, nunca será grande.",
            "Eu sou o melhor jogador do mundo, porque trabalho para ser o melhor todos os dias.",
            "Talento sem dedicação é como uma luz sem eletricidade.",
            "Não quero ser comparado a ninguém, quero criar a minha própria história.",
            "Dedicação, trabalho duro e fé em Deus. É esse o segredo.",
            "As críticas são o combustível para a minha evolução.",
            "Eu vivo para vencer e superarei qualquer obstáculo.",
            "O sucesso não é por acaso. É trabalho duro, perseverança, aprendizado, estudo, sacrifício e, acima de tudo, amor pelo que você está fazendo.",
            "Nenhum jogador pode vencer um jogo sozinho.",
            "Tudo é prática.",
            "Eu nasci para jogar futebol, assim como Beethoven nasceu para escrever música.",
            "O futebol é a música do corpo.",
            "Se você quer ser bem-sucedido, precisa ter uma dedicação total, buscar seu último limite e dar o melhor de si mesmo.",
            "Eu não tenho idolos. Eu admiro o trabalho, a dedicação e a competência.",
            "No que diz respeito ao empenho, ao compromisso, ao esforço, não há meio termo.",
            "O segundo colocado é apenas o primeiro dos perdedores.",
            "Medo é um sentimento que me fascina.",
            "A vitória pertence àqueles que acreditam nela por mais tempo.",
            "Não limite os seus desafios, desafie os seus limites.",
            "A pressão é um privilégio dado aos preparados.",
            "O verdadeiro campeão se reconhece na derrota.",
            "A dor é temporária, o orgulho é eterno.",
            "Onde há determinação, as desculpas desaparecem.",
            "Seja o líder que você gostaria de ter.",
            "Derrota não é o fim, é o recomeço de uma nova estratégia.",
            "O respeito ganha-se no campo, não nas palavras.",
            "Treine enquanto eles dormem, vença enquanto eles duvidam.",
            "A consistência supera a intensidade ocasional.",
            "Um homem sem paixão é apenas um espectador da própria vida.",
            "Não foque nos obstáculos, foque na linha de chegada.",
            "Sua única competição é quem você foi ontem.",
            "Pense grande, comece pequeno, aja agora.",
            "O esforço de hoje é o triunfo de amanhã.",
            "Confie no processo, os resultados virão.",
            "Atitude é uma pequena coisa que faz uma grande diferença.",
            "Vencer sem sacrifício é apenas uma ilusão.",
            "A humildade é a marca dos verdadeiros gigantes.",
            "Faça o que tem de ser feito com excelência.",
            "O fracasso é o combustível dos fortes.",
            "A paixão pelo jogo supera qualquer obstáculo.",
            "A glória não é nunca cair, mas levantar-se sempre.",
            "Deixe o seu legado por onde passar.",
            "Cinquenta anos de progresso em cinco anos de governo.",
            "O otimismo é a força que move o mundo.",
            "Não há progresso sem coragem de inovar.",
            "A liberdade é a coisa mais preciosa que o homem possui.",
            "A cultura de um povo é o seu maior patrimônio.",
            "Escrever é uma forma de lutar pela justiça social.",
            "A democracia é o governo do povo, pelo povo e para o povo.",
            "A justiça é o pilar sobre o qual se constrói uma nação forte.",
            "A paz não é apenas a ausência de guerra, é a presença da justiça.",
            "Povo que não conhece a sua história está fadado a repeti-la.",
            "A igualdade começa pelo respeito às diferenças.",
            "A corrupção destrói as bases da sociedade.",
            "O verdadeiro patriota critica o seu país para melhorá-lo.",
            "A política deve ser uma ferramenta de serviço ao bem comum.",
            "A liberdade de expressão é a salvaguarda de todas as outras liberdades.",
            "Unidos somos mais fortes do que qualquer adversidade.",
            "A honestidade é a primeira página do livro da sabedoria.",
            "O poder sem responsabilidade gera a tirania.",
            "A esperança de um povo reside nas suas crianças.",
            "Trabalhar para o bem coletivo é a maior virtude de um cidadão.",
            "A verdade prevalecerá sobre a mentira, no devido tempo.",
            "A ciência ilumina o caminho da humanidade.",
            "Respeitar o meio ambiente é garantir o futuro da humanidade.",
            "A tolerância é o alicerce da convivência pacífica.",
            "Nenhum homem é uma ilha, inteira em si mesma.",
            "A lei deve ser igual para todos, sem exceções.",
            "A mudança social começa com a conscientização individual.",
            "O progresso moral deve acompanhar o progresso material.",
            "Proteger os mais vulneráveis é a marca de uma civilização avançada.",
            "A sabedoria política reside no equilíbrio entre tradição e inovação.",
            "A arte é o espelho da alma de uma nação.",
            "Não há vitória real quando o preço é a perda da dignidade.",
            "O diálogo é a única ponte para superar os conflitos.",
            "Servir com integridade é a maior honra.",
            "A memória histórica é o antídoto contra o esquecimento.",
            "A solidariedade transforma sociedades.",
            "Construir pontes é melhor do que erguer muros.",
            "A verdade não tem medo do questionamento.",
            "O trabalho dignifica o homem e constrói o futuro.",
            "Um país educado é um país invencível.",
            "A coragem de defender o certo, mesmo quando se está sozinho.",
            "A história julgará a todos com imparcialidade.",
            "A paz é o único caminho para a prosperidade duradoura.",
            "Investir na juventude é semear o futuro.",
            "A justiça tardia é uma forma de injustiça.",
            "A empatia é a chave para a compreensão humana.",
            "Sonhar com um mundo melhor é o primeiro passo para construí-lo.",
            "O tempo coloca cada coisa no seu devido lugar.",
            "O segredo da felicidade é a liberdade, e o segredo da liberdade é a coragem.",
            "A vida não é sobre esperar a tempestade passar, é sobre aprender a dançar na chuva.",
            "Nem todos os caminhos são fáceis, mas todos ensinam algo.",
            "Sorria, o sorriso abre portas que nenhuma chave consegue abrir.",
            "Quem cultiva amor, colhe paz.",
            "O tempo que você gosta de perder não é tempo perdido.",
            "A beleza atrai a atenção, mas o caráter conquista o coração.",
            "Pequenos gestos podem mudar o dia de alguém.",
            "A humildade é a chave que abre a porta do conhecimento.",
            "Viver é reinventar-se a cada amanhecer.",
            "Não julgue o livro pela capa, nem o homem pelas aparências.",
            "A paciência é uma virtude que poucos dominam, mas que todos precisam.",
            "Onde há amor, há vida.",
            "As melhores coisas da vida não são coisas, são momentos.",
            "Faça do seu dia uma obra-prima.",
            "A fé move montanhas, mas a ação constrói caminhos.",
            "Nada é permanente neste mundo, nem mesmo os nossos problemas.",
            "A gentileza é uma linguagem que os surdos podem ouvir e os cegos podem ver.",
            "Aprenda com o passado, viva o presente, sonhe com o futuro.",
            "O amor é o único sentimento que cresce quando se divide.",
            "A dúvida é o princípio da sabedoria.",
            "Não conte os dias, faça os dias contarem.",
            "O que não te derruba, te fortalece.",
            "Colecione memórias, não coisas.",
            "O perdão liberta a alma e apaga o medo.",
            "Seja forte e corajoso, não desista dos seus objetivos.",
            "O destino é o resultado das nossas próprias escolhas.",
            "Rir de si mesmo é o melhor remédio para o estresse.",
            "A amizade duplica as alegrias e divide as tristezas.",
            "A sabedoria vem com a experiência, e a experiência com os erros.",
            "Nada acontece por acaso, tudo tem o seu tempo certo.",
            "A maior vitória é conquistar a si mesmo.",
            "Mentes abertas criam novos caminhos.",
            "O respeito é a base de qualquer relacionamento saudável.",
            "Transforme os seus obstáculos em degraus para o sucesso.",
            "A vida é curta demais para viver os sonhos dos outros.",
            "O conhecimento não ocupa espaço, mas expande o seu mundo.",
            "Sem paixão, a vida perde a sua cor.",
            "A paz de espírito é o maior tesouro que podemos possuir.",
            "Sempre há algo novo para aprender a cada dia.",
            "Acredite no seu potencial e o mundo acreditará em você.",
            "O mundo inteirinho fica cheio de graça e fica mais lindo por causa do amor.",
            "Vai minha tristeza e diz a ela que sem ela não pode ser.",
            "Diz-lhe numa prece pra ela regressar, porque eu não posso mais sofrer.",
            "Chega de saudade, a realidade é que sem ela não há paz.",
            "Este samba que é misto de maracatu, é samba de preto velho, samba de preto tu.",
            "Se você diz que eu desafio, amor, saiba que isto em mim provoca imensa dor.",
            "Só privilégio têm os desafinados também têm um coração.",
            "No peito dos desafinados também bate um coração.",
            "Muita calma pra pensar, e ter tempo pra sonhar.",
            "É pau, é pedra, é o fim do caminho.",
            "São as águas de março fechando o verão, é a promessa de vida no teu coração.",
            "Tristeza não tem fim, felicidade sim.",
            "A felicidade é como a gota de orvalho numa pétala de flor.",
            "Ah, se ela soubesse que quando ela passa, o mundo sorri.",
            "Canta forte, canta alto, que a vida vai melhorar.",
            "Eu sei que vou te amar, por toda a minha vida eu vou te amar.",
            "Em cada despedida a certeza de que eu vou voltar.",
            "Por minha lei a gente era obrigado a ser feliz.",
            "Um abraço e um beijo, e um carinho sem fim.",
            "Quando a gente gosta, o amor não se mede.",
            "Sem amor, a vida é apenas uma ilusão.",
            "Que a paz reine em nosso coração hoje e sempre.",
            "Amou daquela vez como se fosse a última.",
            "Beijou sua mulher como se fosse a última.",
            "E ergueu no patamar quatro paredes sólidas.",
            "Morreu na contramão atrapalhando o tráfego.",
            "Ainda bem que você chegou, pra me salvar do meu próprio medo.",
            "O meu coração já não aguenta mais tanta solidão.",
            "Junto de você tudo fica tão leve.",
            "O tempo passou e nosso amor prevaleceu.",
            "Às vezes no silêncio da noite eu fico imaginando nós dois.",
            "Por que você me deixa tão solto?",
            "Por que você não cola em mim?",
            "Quando a gente ama, claro que a gente cuida.",
            "Porque se você parar pra pensar, na verdade não há.",
            "Sou uma gota d'água, sou um grão de areia.",
            "Gosto de te ver ao sol, leãozinho.",
            "Para entreter o meu coração, deu a pérola do teu olhar.",
            "Meu coração é teu e o teu coração é meu.",
            "O mundo é um moinho, vai triturar teus sonhos.",
            "Preste atenção, o mundo é um moinho.",
            "Quem sabe um dia a gente se encontra por aí.",
            "Meu abraço é o teu abrigo no meio da tempestade.",
            "E no meio de tanta gente, eu encontrei você.",
            "Nada do que foi será do jeito que já foi um dia.",
            "Tudo passa, tudo sempre passará.",
            "Viver e não ter a vergonha de ser feliz.",
            "Eu fico com a pureza da resposta das crianças.",
            "É a vida, é bonita e é bonita.",
            "Amar é um ato de coragem em um mundo frio.",
            "A distância nunca vai apagar o que sentimos.",
            "Sua lembrança é uma canção suave na minha mente.",
            "O amor transforma o ordinário em extraordinário.",
            "Com você, cada segundo vale uma eternidade.",
            "Nossa, nossa, assim você me mata!",
            "Ai, se eu te pego, ai, ai, se eu te pego!",
            "E nessa loucura de dizer que não te quero, vou negando as aparências, disfarçando as evidências.",
            "Mas pra que viver fingindo, se eu não posso enganar meu coração?",
            "Eu sei que te amo! Chega de mentiras, de me negar o seu amor.",
            "Diz que é verdade, que tem saudade, que ainda pensa muito em mim.",
            "Tchê tcherere tchê tchê, Gusttavo Lima e você!",
            "Eu quero curtir, eu quero me apaixonar.",
            "Bum bum tam tam, vem com a flauta envolvente!",
            "Prepara que agora é a hora do show das poderosas!",
            "Desce, rebola, vem mostrando como faz.",
            "Hoje é dia de baile, ninguém fica parado.",
            "Se a gente não der certo, a gente tenta de novo.",
            "A sofrência é grande, mas a cerveja é gelada.",
            "Trocou meu amor por uma ilusão de momento.",
            "Hoje eu tô daquele jeito, pronto pra farra.",
            "O coração chora, mas o corpo dança.",
            "Eu jurei não te ligar, mas o álcool não deixa.",
            "Amor de balada não dura até o amanhecer.",
            "Ela é malvada, sabe como me provocar.",
            "A vida solteira não é para os fracos.",
            "Toca aquela música sofrida de novo, garçom!",
            "Se você me chamar, eu vou correndo.",
            "Esse sorriso seu é minha fraqueza.",
            "Nossa história dá um livro de amor.",
            "Perdi o rumo, perdi a cabeça por você.",
            "A noite é uma criança e a gente quer viver.",
            "A saudade é o preço que se paga por viver bons momentos.",
            "Não manda mensagem de madrugada se não for pra ficar.",
            "Te amar é fácil, o difícil é te esquecer.",
            "Se o amor acabou, o que resta é dançar.",
            "Seu cheiro ficou no meu casaco.",
            "O copo tá cheio, mas o coração tá vazio.",
            "Foi bonito enquanto durou.",
            "Minha vida sem você é um show sem público.",
            "Eu nasci pra te amar e ninguém vai mudar isso.",
            "Liguei só pra ouvir a sua voz.",
            "O amor que sinto por você não cabe no meu peito.",
            "Chove lá fora e aqui dentro é só você.",
            "Você é a dose certa de loucura que eu preciso.",
            "Quem ama cuida, não deixa ir embora.",
            "A gente se entende no olhar.",
            "Foi Deus que deu voz ao vento, e luz ao olhar.",
            "Há bem e mal no meu fado, mas fado é o meu destino.",
            "Amar pelos dois, se o teu coração não quiser amar.",
            "Meu fado meu, que renasce a cada amanhecer.",
            "Ó gente da minha terra, por que chora o vosso fado?",
            "Desfado é cantar a vida sem medo do destino.",
            "Lisboa não se explica, sente-se no coração.",
            "O mar salgado, quanto do teu sal são lágrimas de Portugal?",
            "Navegar é preciso, viver não é preciso.",
            "Fado não se canta, o fado acontece.",
            "Saudade é a dor que fica quando o amor vai embora.",
            "Lisboa, cidade de luz e de saudade.",
            "Nas pedras da calçada está escrita a nossa história.",
            "Perder-se em Lisboa é encontrar-se a si mesmo.",
            "A vida é um barco à deriva no mar do tempo.",
            "Amor de longe, água em cesto.",
            "Canta o fado e chora a alma, amanhã será outro dia.",
            "Trazes o mar nos teus olhos e o vento na tua voz.",
            "A despedida doeu, mas o reencontro será doce.",
            "O que importa é ser feliz, o resto a gente corre atrás.",
            "A vida me ensinou a nunca desistir, nem voltar atrás.",
            "Onde quer que eu vá, o que quer que eu faça, vou levar você comigo.",
            "Liberdade é poder escolher o próprio caminho.",
            "Não deixe o samba morrer, não deixe o samba acabar.",
            "O morro foi feito de samba, de samba pra gente cantar.",
            "O futuro é uma folha em branco esperando por nós.",
            "Cada cicatriz conta uma história de superação.",
            "Acredite nos seus sonhos, eles sabem o caminho.",
            "A coragem não é a ausência de medo, é seguir em frente apesar dele.",
            "Siga o seu coração, ele nunca se engana.",
            "O amor é a força mais poderosa do universo.",
            "A paz começa com um simples sorriso.",
            "Tudo o que precisamos é de amor e um pouco de música.",
            "Nenhum obstáculo é grande demais para quem tem fé.",
            "O mundo muda com o seu exemplo, não com a sua opinião.",
            "Nunca é tarde demais para recomeçar.",
            "A música salva a alma nos dias mais escuros.",
            "Sorria para a vida e ela sorrirá de volta para você.",
            "Onde há música, há esperança.",
            "Que a nossa música toque o coração do mundo inteiro.",
            "Aumenta o som, que a vida é curta e a música não pode parar!",
            "Massa",
            "Massa D+",
            "Top",
            "Misto / Misto quente",
            "Biscoiteiro / Biscoiteira",
            "Biscoitar",
            "Cringe",
            "Lenda",
            "Crush",
            "Gatinho / Gatinha",
            "Gato / Gata",
            "Pegar",
            "Ficar",
            "Ficante",
            "Shippar",
            "Gado / Gadagem",
            "Vácuo",
            "Talarico / Talarica",
            "Nossa! / Nossa senhora!",
            "Eita!",
            "Oxente! / Oxe!",
            "Aff!",
            "Caraca!",
            "Caramba!",
            "Poxa! / Poxa vida!",
            "Nossa, nada a ver!",
            "Lacrou! / Lacração",
            "Arrasou!",
            "Mitar",
            "Mito",
            "Rolê / Rolê aleatório",
            "Flopar",
            "Cancelado / Cancelar",
            "Trollar",
            "Hater",
            "Meme",
            "Stalkear",
            "Pagar mico",
            "Mico",
            "Sextou!",
            "Maratonar",
            "Tirar onda",
            "Mandar mal",
            "Deu ruim!",
            "Deu bom!",
            "Sem crise!",
            "Pode crê!",
            "Com certeza!",
            "Partiu burger?",
            "Tô nem aí!",
            "Fala sério!",
            "Tô bege!",
            "Sua cara!",
            "Bro",
            "Brother",
            "Malandro",
            "Novinha / Novinho",
            "Cria",
            "Parceiragem",
            "Baile funk",
            "Fluxo",
            "Ostentar",
            "Bater um papo",
            "Jogar conversa fora",
            "Desencana!",
            "Nóia",
            "Noiado",
            "Surtar",
            "Surtado / Surtada",
            "Lacrar",
            "Hablou!",
            "Grana",
            "Grana preta",
            "Estar duro / Estar sem grana",
            "Pão-duro",
            "Mão de vaca",
            "Dar um migué",
            "Com certeza, mano!",
            "Pagar pau",
            "Meter o louco",
            "Viajar na maionese",
            "Viajou!",
            "Dar bode",
            "Dar ruim",
            "Queimar o filme",
            "Encher o saco",
            "Saco cheio",
            "Chorar as pitangas",
            "Pipocar",
            "Amarelar",
            "Gente boa",
            "Cara de pau",
            "Sem Noção",
            "Mandar a real",
            "Estar no sal",
            "Dar a volta por cima",
            "Pisar na bola",
            "Comer bola",
            "Bola pra frente!",
            "Tirar a limpo",
            "Fazer vaquinha",
            "Bater as botas",
            "Engolir sapo",
            "Procurar em pelo em ovo",
            "Tirar o cavalo da chuva",
            "Dar murro em ponta de faca",
            "Nossa, que babado!",
            "Fazer tempestade em copo d'água",
            "Gajo / Gaja",
            "PPL",
            "Bué",
            "Fixe",
            "Giro / Gira",
            "Bébé",
            "Tipo...",
            "Fixelândia",
            "Pá",
            "Geringonça",
            "Nómada digital",
            "Chular",
            "Estar com a macaca",
            "Copo de água",
            "Dar a sola",
            "Melão",
            "Esquece!",
            "Tudo bem, pá?",
            "Que cena!",
            "Estar de grilo",
            "Dar graxa",
            "Bater mal",
            "Estar à nora",
            "Curtir",
            "Passar as passinhas do Algarve",
            "Ter lata",
            "Ir à falência",
            "Estar nas tintas",
            "Dar o cavaquinho",
            "Ficar a ver navios",
            "Dar com a língua nos dentes",
            "Com certeza, pá!",
            "vc",
            "tb / tbm",
            "q",
            "pq",
            "pq?",
            "mto",
            "qdo",
            "vlw",
            "flw",
            "tmj",
            "kkkkk",
            "rsrsrs",
            "hahaha",
            "misericórdia!",
            "Gente?!",
            "Bora lá",
            "Partiu Cama!",
            "Tô a caminho",
            "Aonde cê vai?",
            "Aí sim!",
            "Faz sentido",
            "Nossa, sim!",
            "Tô pronto",
            "Bora marcar!",
            "Depois a gente se fala",
            "LINK NA BIO",
            "Segue o fluxo",
            "Zero noção",
            "Passo mal!",
            "Tô me tremendo!",
            "Que mico!",
            "Tô suave",
            "Fechou!",
            "É nós!",
            "Tamo junto e misturado!",
    };

    public SemanticMatcherPt(Context context) {
        super(context, TAG, ASSET_PATH, FALLBACK_QUESTIONS, randomActions());
    }

    /** fallback 動作全部 __RANDOM__：幾多答句就幾多個位，SemanticCenter
     *  見到呢個標記會即場隨機選動作 (見 ActionDirect.resolveRandomActionId())。 */
    private static String[] randomActions() {
        String[] a = new String[FALLBACK_QUESTIONS.length];
        for (int i = 0; i < a.length; i++) {
            a[i] = "__RANDOM__";
        }
        return a;
    }
}
