package com.open.alpha2;

import android.content.Context;

/**
 * 意大利文語意配對引擎 - 和 SemanticMatcherZh (中文版)／SemanticMatcherEn
 * (英文版)／SemanticMatcherEs (西班牙文版)／SemanticMatcherFr (法文版)／
 * SemanticMatcherJa (日文版) 同一套語意配對機制, 專門處理意大利文。
 *
 * 骨架：assets/semantic/semantic_it.json 目前有 85 ACTION (id/op/slot/actionId
 * 全同英文版；每組意大利文 5 問法＋5 答案) ＋200 日常 CHAT (it.daily.001-200，
 * 每組 5 問法＋5 答案：001-040 問候天氣、041-080 飲食、081-120 家庭家居寵物、
 * 121-160 工作學習健康、161-200 休閒旅行日常；動作全 __RANDOM__)。
 * it800（電影 200／名言 200／歌詞 198／潮語 200）啱意境的
 * 已按意配入日常組答案（每組最多加 3 句）；19 句粗口／暴力／威脅剔除唔用；
 * 剩低 568 句全入下面 fallback，動作全 __RANDOM__（60 池）。
 *
 * 這個 class 只負責「文字 -> 配對結果」, 不負責執行 TTS/動作 - 跟著這個 project
 * 一貫的分層方式，執行那一步留給呼叫方 (SemanticCenter 的 handleSemanticMatch)
 * 做, 方便測試和重用。
 *
 * 只做意大利文 - 和其他語言版各自獨立, 沒在這個 class 裡加 language 參數
 * (因為機身 ASR 引擎本身一次只能選到一種語言, matcher 不會同時用）。
 * SemanticCenter.handleSemanticMatch() 根據對話語言／文字判斷結果, 選用哪一個。
 * 載入/比對/分類 random 的實際邏輯全部在 SemanticMatcherBase, 這裡只提供
 * 意大利文專屬的 TAG/assets 路徑/fallback 問法組。
 *
 * Zero-third-party-dependency: 只用 org.json (Android 內建, 經 base class), 沒額外
 * library。
 */
public class SemanticMatcherIt extends SemanticMatcherBase {
    private static final String TAG = "SemanticMatcherIt";
    private static final String ASSET_PATH = "semantic/semantic_it.json";

    /** 骨架：fallback 空池（內容後加；base.fallback() 空池回 null，唔 crash）。 */
    private static final String[] FALLBACK_QUESTIONS = {
            "Abbiamo vinto!",
            "Non tornare più, non cedere alla nostalgia.",
            "Ho voglia di te.",
            "Il segreto di tutto è l'amore.",
            "Finisce sempre così. Con la morte. Prima, però, c'è stata la vita.",
            "Gli uomini passano, le idee restano.",
            "Io vedo gente morta.",
            "L'amore non ha età.",
            "Siamo tutti frangibili.",
            "Ognuno di noi ha tre vite: una pubblica, una privata e una segreta.",
            "Chi cerca trova.",
            "Ti farò un'offerta che non potrà rifiutare.",
            "Ti amo più della mia stessa vita.",
            "Senza di te non sono niente.",
            "Voglio passare il resto della mia vita con te.",
            "Il mio cuore appartiene a te.",
            "Sei il mio primo e ultimo pensiero della giornata.",
            "Non riesco a smettere di pensarti.",
            "Sei il sogno che non sapevo di avere.",
            "L'amore è un'arte.",
            "Baciami come se fosse l'ultima volta.",
            "Con te il tempo si ferma.",
            "Sei l'unica persona che mi capisce veramente.",
            "Mi hai cambiato la vita.",
            "Non c'è spazio per nessun altro nel mio cuore.",
            "L'amore non si spiega, si vive.",
            "Siamo fatti l'uno per l'altra.",
            "Tu sei il mio destino.",
            "C'è un filo invisibile che ci unisce.",
            "Non me ne andare, resta con me.",
            "Guardami negli occhi e dimmi la verità.",
            "Sei il miglior sbaglio della mia vita.",
            "Non posso prometterti l'eternità, ma posso darti tutto il mio tempo.",
            "Ogni volta che ti vedo, mi innamoro di nuovo.",
            "Tu mi completi.",
            "Nessun oceano potrà mai separarci.",
            "Niente accade per caso.",
            "Tutti cambiano, basta solo un po' di tempo.",
            "L'unica costante della vita è il cambiamento.",
            "Le persone non cambiano, mostrano solo chi sono veramente.",
            "Il Silenzio a volte dice più delle parole.",
            "Non rompermi le scatole.",
            "Mamma mia, che disastro!",
            "Tutto va a rotoli.",
            "Chi se ne frega!",
            "Stai zitto per un minuto, per favore!",
            "Sei un disastro ambulante.",
            "Ci manca solo questo!",
            "Non gettare la spugna.",
            "Piove sempre sul bagnato.",
            "Prendi due piccioni con una fava.",
            "L'abito non fa il monaco.",
            "Non fare un passo avanti!",
            "Ho io il controllo della situazione.",
            "Non c'è tempo da perdere, andiamo!",
            "Chi ti ha mandato?",
            "Mi hai tradito!",
            "È stato un trappola fin dall'inizio.",
            "La vendetta è un piatto che va servito freddo.",
            "Tieni i tuoi amici vicini, ma i tuoi nemici ancora più vicini.",
            "Dove sono i documenti?",
            "Coprimi le spalle!",
            "Niente è come sembra.",
            "È troppo pericoloso.",
            "Sono fiero di te.",
            "Dammi una seconda possibilità.",
            "Facciamo finta che non sia successo niente.",
            "Tutto si sistemerà.",
            "Sono qui per te.",
            "Non sei solo.",
            "La vita va avanti.",
            "Spero che tu sia felice.",
            "Non ho parole.",
            "Cosa c'è che non va?",
            "Ho fatto tutto quello che potevo.",
            "Incrociamo le dita!",
            "Speriamo bene.",
            "Non vedo l'ora!",
            "Sii forte.",
            "Non mollare mai.",
            "Segui il tuo cuore.",
            "La verità viene sempre a galla.",
            "Non cambiare mai.",
            "Tieni duro!",
            "Non c'è motivo di preoccuparsi.",
            "Sono mortificato.",
            "È stato un onore.",
            "Tutto ha un prezzo.",
            "Resta come sei.",
            "Il futuro ci appartiene.",
            "La vita è bella.",
            "Chi parla poco, sa molto.",
            "Non si vive se non il tempo che si ama.",
            "Vivere non è abbastanza... ci vuole il sole, la libertà e un piccolo fiore.",
            "Chi cerca trova, chi segue insegue.",
            "Il saggio parla perché ha qualcosa da dire, il stolto perché deve dire qualcosa.",
            "Niente è permanente, tranne il cambiamento.",
            "La felicità è una scelta, non un risultato.",
            "Chiusa una porta, si apre un portone.",
            "La verità vi renderà liberi.",
            "Nessuno può farti sentire inferiore senza il tuo consenso.",
            "Il tempo guarisce tutte le ferite.",
            "Non pentirti mai di ciò che hai fatto se eri felice mentre lo facevi.",
            "Tutto è relativo.",
            "Sapere è potere.",
            "La pazienza è la virtù dei forti.",
            "Meglio tardi che mai.",
            "Chi non risica, non rosica.",
            "La vita è un'opera di teatro che non ha prove in costume.",
            "La bellezza salverà il mondo.",
            "Fai della tua vita un sogno, e di un sogno, una realtà.",
            "Chi non ama la solitudine, non ama la libertà.",
            "L'esperienza è il maestro di tutte le cose.",
            "Chi ha un perché per vivere può sopportare quasi ogni come.",
            "Vivi e lascia vivere.",
            "Il silenzio è un'arte grande quanto quella del parlare.",
            "Non rimandare a domani quello che puoi fare oggi.",
            "La semplicità è l'ultima sofisticazione.",
            "Saper vedere.",
            "I dettagli fanno la perfezione e la perfezione non è un dettaglio.",
            "Chi poco pensa, molto erra.",
            "Nessuna cosa si può amare né odiare, se prima non si ha cognizione di quella.",
            "L'ostacolo non mi piega, ogni ostacolo si sottomette alla rigidità.",
            "L'amore supremo è la comprensione.",
            "Ho visto l'angelo nel marmo e ho scolpito fino a liberarlo.",
            "Non si può avere una padronanza maggiore o minore di quella che si ha su se stessi.",
            "La pittura è una poesia muta, e la poesia è una pittura cieca.",
            "L'acqua che tocchi è l'ultima che è passata e la prima che viene. Così il tempo presente.",
            "Se la gente sapesse quanto ho lavorato duro per ottenere la mia maestria, non sembrerebbe affatto così meravigliosa.",
            "La vita ben spesa miete una lunga e felice morte.",
            "Dove la natura finisce di produrre le sue specie, l'uomo comincia con le cose naturali a far infinite specie.",
            "Il più grande pericolo per la maggior parte di noi non è che il nostro obiettivo sia troppo alto e lo manchiamo, ma che sia troppo basso e lo raggiungiamo.",
            "Così come una giornata ben spesa dà un lieto dormire, così una vita ben usata dà un lieto morire.",
            "La mente vola, le mani lavorano.",
            "Niente può essere amato o odiato senza essere prima compreso.",
            "Chi non stimano la vita, non la meritano.",
            "La creatività è l'intelligenza che si diverte.",
            "Non si dipinge con le mani, ma col cervello.",
            "L'arte è la regina di tutte le scienze che comunicano la conoscenza a tutte le generazioni del mondo.",
            "Ogni blocco di pietra ha una statua dentro di sé ed è compito dello scultore scoprirla.",
            "Selvaggia è la passione di chi ama senza misura.",
            "Un giorno senza un sorriso è un giorno perso.",
            "Il ferro arrugginisce se non usato, l'acqua si putrefà... così l'ingegno senza esercizio.",
            "Il mio disegno è libero.",
            "La natura è piena di infinite ragioni che non furon mai in esperienza.",
            "Considerate la vostra semenza: fatti non foste a viver come bruti, ma per seguir virtute e canoscenza.",
            "Considerate la vostra natura, non siete nati per vivere come bruti.",
            "Lasciate ogne speranza, voi ch'intrate.",
            "L'amor che move il sole e l'altre stelle.",
            "Non ti curar di lor, ma guarda e passa.",
            "Il fine giustifica i mezzi.",
            "È molto più sicuro essere temuto che amato.",
            "Ognuno vede quel che tu appari, pochi sentono quel che tu sei.",
            "La fortuna è donna, ed è necessario, volendola tenere sotto, batterla e urtarla.",
            "Non c'è niente di più difficile da gestire... del creare un nuovo ordine di cose.",
            "Nessun grande ingegno è mai esistito senza un pizzico di follia.",
            "La vita non è quella che si è vissuta, ma quella che si ricorda.",
            "Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura.",
            "Libertà va cercando, ch'è sì cara, come sa chi per lei vita rifiuta.",
            "Perder tempo a chi più sa più spiace.",
            "Poca favilla gran fiamma seconda.",
            "Se 'l mondo presente t'è in grado, godilo.",
            "Gli uomini offendono prima chi amano che chi temono.",
            "Gli uomini si dimenticano più presto della morte del padre che della perdita del patrimonio.",
            "Colui che controlla il passato controlla il futuro.",
            "La parola usata bene è un’arma affilata.",
            "Il libro è una creatura fragile, soffre il tempo, teme i barbari.",
            "Così tra questa immensità s'annega il pensier mio: e il naufragar m'è dolce in questo mare.",
            "Il mondo è un libro e chi non viaggia ne legge solo una pagina.",
            "Nessun uomo è un'isola.",
            "Non si vede bene che col cuore. L'essenziale è invisibile agli occhi.",
            "Ciò che non mi distrugge mi rende più forte.",
            "Il destino mescola le carte, e noi giochiamo.",
            "C'è una maschera per ogni volto e una solitudine in ogni cuore.",
            "Imparerai a tue spese che nel lungo tragitto della vita incontrerai molte maschere e pochi volti.",
            "Eppur si muove.",
            "Le cose sono unite da legami invisibili: non puoi cogliere un fiore senza turbare una stella.",
            "La matematica è l'alfabeto in cui Dio ha scritto l'universo.",
            "Non puoi insegnare niente a un uomo; puoi solo aiutarlo a scoprirlo dentro di sé.",
            "Misura ciò che è misurabile, e rendi misurabile ciò che non lo è.",
            "In questioni di scienza, l'autorità di migliaia di opinioni non vale il piccolo scintillio del cervello di un singolo individuo.",
            "Tutte le verità sono facili da capire una volta che sono state scoperte; il punto è scoprirle.",
            "Dietro ogni problema c'è un'opportunità.",
            "Dove l'esperimento manca, la teoria è vana.",
            "L'ignoranza è la madre dell'insolenza.",
            "Fatti non foste a viver come bruti, ma per seguir virtute e canoscenza.",
            "La scienza è il grande anticorpo contro il veleno dell'entusiasmo e della superstizione.",
            "Non c'è grande genio senza un pizzico di follia.",
            "Il dubbio è il padre dell'invenzione.",
            "Non puoi insegnare nulla a nessuno, puoi solo aiutarlo a trovarlo in se stesso.",
            "Natura non facit saltus.",
            "Comprendere è l'inizio dell'approvazione.",
            "Nulla si crea, nulla si distrugge, tutto si trasforma.",
            "Sapere aude! Abbi il coraggio di servirti della tua propria intelligenza!",
            "L'uomo è la misura di tutte le cose.",
            "Cogito, ergo sum.",
            "La ragione è la luce dell'anima.",
            "Non c'est la natura che ci inganna, siamo noi che c'inganniamo.",
            "Chi dubita, pensa; chi pensa, esiste.",
            "L'universo è un libro scritto in lingua matematica.",
            "La verità è figlia del tempo, non dell'autorità.",
            "Cerca la verità e la verità ti farà libero.",
            "Un’idea non è niente finché non diventa un’azione.",
            "Niente ha potere su di te se non ciò che gli permetti.",
            "L'arte della memoria è la chiave del sapere.",
            "La vita è un film, e la regia è tua.",
            "Un diverso linguaggio è una diversa visione della vita.",
            "Non c'est la fine. Non è nemmeno l'inizio della fine. Ma è, forse, la fine dell'inizio.",
            "La cinematografia è la scrittura con le immagini.",
            "Nulla si sa, tutto si immagina.",
            "Non c'è niente di più reale dell'illusione.",
            "Parla piano, se parli d'amore.",
            "La moda passa, lo stile resta.",
            "L'eleganza non è farsi notare, ma farsi ricordare.",
            "La semplicità è la nota fondamentale di ogni vera eleganza.",
            "La legge della vita è il cambiamento.",
            "Sii il cambiamento che vuoi vedere nel mondo.",
            "L'arte non riproduce ciò che è visibile, ma rende visibile ciò che non sempre lo è.",
            "La musica è l'architettura dei suoni.",
            "Senza la musica, la vita sarebbe un errore.",
            "L'unica vera saggezza è sapere di non sapere nulla.",
            "La felicità non è qualcosa di fatto. Viene dalle tue azioni.",
            "Sogna come se dovessi vivere per sempre. Vivi come se dovessi morire oggi.",
            "Vivere significa cambiare, e essere perfetti significa essere cambiati spesso.",
            "Il bello dell'arte è che non ha limiti.",
            "La musica può cambiare il mondo perché può cambiare le persone.",
            "Non contano gli anni della tua vita, ma la vita nei tuoi anni.",
            "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.",
            "Non camminare davanti a me, potrei non seguirti. Cammina al mio fianco e sii mio amico.",
            "La creatività richiede coraggio.",
            "Tutto ciò che puoi immaginare è reale.",
            "L'arte spazza via dall'anima la polvere della vita quotidiana.",
            "La risposta, amico mio, sta soffiando nel vento.",
            "Il cinema è un sogno che si sogna insieme.",
            "La semplicità è il massimo della raffinatezza.",
            "La moda è quello che compri, lo stile è quello che fai con esso.",
            "L'eleganza è la sola bellezza che non sfiorisce mai.",
            "Vivere senza tentare è come non essere mai nati.",
            "Il successo è l'invidia degli altri.",
            "La risata è il sole che scaccia l'inverno dal volto umano.",
            "Ciò che fai oggi può migliorare tutti i tuoi domani.",
            "L'amore non guarda con gli occhi ma con l'anima.",
            "Ama e fai ciò che vuoi.",
            "L'amore è la forza più potente del mondo.",
            "Dove c'est amore, c'è vita.",
            "L'amore vero non ha mai fine.",
            "Chi ama, crede.",
            "Non c'è rimedio all'amore se non amare di più.",
            "L'amore vincit omnia.",
            "C'è solo una felicità nella vita: amare ed essere amati.",
            "Il cuore ha le sue ragioni, che la ragione non conosce.",
            "Un amico è qualcuno che sa tutto di te e ti ama lo stesso.",
            "L'amore è un'anima sola che abita in due corpi.",
            "Si vive una volta sola, ma se lo fai bene, una volta è abbastanza.",
            "Niente è impossibile per chi ci prova.",
            "L'unico modo per fare un ottimo lavoro è amare quello che fai.",
            "Se puoi sognarlo, puoi farlo.",
            "Il modo migliore per predire il futuro è crearlo.",
            "Fai quello che puoi, con quello che hai, dove sei.",
            "L'unica certezza è la nostra capacita di superare le sfide.",
            "La speranza è l'ultima a morire.",
            "A caval donato non si guarda in bocca.",
            "Tutte le strade portano a Roma.",
            "Il lupo perde il pelo ma non il vizio.",
            "Meglio solo che male accompagnato.",
            "Non è tutto oro quel che luccica.",
            "Ride bene chi ride ultimo.",
            "Chi trova un amico, trova un tesoro.",
            "Tra il dire e il fare c'è di mezzo il mare.",
            "La goccia scava la pietra.",
            "Veni, vidi, vici.",
            "La fortuna aiuta gli audaci.",
            "Carpe diem.",
            "In vino veritas.",
            "La calunnia è un venticello.",
            "Senza musica la vita sarebbe un errore.",
            "L'uomo è un animale sociale.",
            "La verità trionfa sempre.",
            "Con te partirò, paesi che non ho mai visto e vissuto con te.",
            "Caruso, te voglio bene assai, ma tanto tanto bene sai.",
            "La solitudine fra noi, questo silenzio dentro me.",
            "Marco se ne è andato e non ritorna più.",
            "Sei nell'anima e lì ti lascio per sempre.",
            "Più bella cosa non c'è, più bella cosa di te.",
            "Cose della vita, vanno prese così.",
            "Senza una donna, come siamo lontani.",
            "Bello e impossibile, con gli occhi neri e quella bocca da baciare.",
            "Vivo per lei da quando sai, la prima volta l'ho incontrata.",
            "Gocce di memoria nei labirinti del mio cervello.",
            "Come saprei amarti io, nessuno mai.",
            "L'emozione non ha voce.",
            "Io non so parlare d'amore, l'emozione non ha voce.",
            "Ti amo, un soldo ti amo, in aria ti amo.",
            "Gloria, manchi tu nell'aria.",
            "Tu sei l'unica donna per me.",
            "Se telefonando io potessi dirti addio, ti chiamerei.",
            "Grande, grande, grande come te.",
            "Mi ritorni in mente, bella come sei.",
            "Ancora tu, non mi sorprende lo sai.",
            "Emozioni, che salgono piano piano.",
            "Amore mio, bastano poche parole.",
            "Voi non sapete di cosa parlo, voi non sapete cosa ho dentro.",
            "Parla, la gente purtroppo parla, non sa di che cosa parla.",
            "Occidentali's Karma, la scimmia s'innalza.",
            "Comprami, io sono in vendita.",
            "Supereroi, tutti noi siamo supereroi.",
            "Cenere, la nostra storia finisce in cenere.",
            "Due vite, tra la terra e il cielo.",
            "L'essenziale, che non c'è bisogno di niente.",
            "Luce, il tempo di un respiro.",
            "Oltre le sponde del mondo.",
            "A te che sei il mio grande amore ed il mio amore grande.",
            "A te che sei, semplicemente sei, sostanza dei giorni miei.",
            "L'ombelico del mondo, dove si incrociano le strade.",
            "Bella ciao, bella ciao, bella ciao ciao ciao!",
            "Una mattina mi son svegliato, e ho trovato l'invasor.",
            "O partigiano, portami via, ché mi sento di morire.",
            "E se io muoio da partigiano, tu mi devi seppellire.",
            "Seppellire lassù in montagna, sotto l'ombra di un bel fior.",
            "Core 'ngrato, tu nne mme pienze cchiù.",
            "Catari', Catari', pecchè me dici sti parole amare?",
            "Dicitencello a 'sta cumpagna vosta.",
            "Anema e core, tenimmece pe' mano.",
            "Reginella, quanno stive cu mme...",
            "Canzone, stasera voglio cantare una canzone.",
            "Attenti al lupo, attenti al cane.",
            "Gli anni d'oro del grande Real...",
            "Voglio una vita spericolata, di quelle vite fatte così.",
            "Gianna, Gianna, Gianna sosteneva le sue tesi.",
            "La canzone di Marinella, questa è la tua canzone.",
            "Dai diamanti non nasce niente, dal letame nascono i fior.",
            "Fiume Sand Creek, si sciolse il sangue nel fiume.",
            "Don Raffaè, io me ne intendo di caffè.",
            "Samarcanda, oh Samarcanda!",
            "Luci a San Siro, di questa sera.",
            "Chiamami ancora amore, quando la notte sfuma.",
            "Superficie di un oceano di pace.",
            "Voglio vederti danzare, come le zingare nel deserto.",
            "Cuccurucucù paloma, ahia-ia-ia-iai cantava.",
            "Diletta la mia sposa, all'alba vincerò!",
            "Vincerò! Vincerò!",
            "E lucevan le stelle, ed olezzava la terra.",
            "O mio babbino caro, mi piace, è bello, bello.",
            "La donna è mobile, qual piuma al vento.",
            "Libiamo ne' lieti calici.",
            "Amor, ch'a nullo amato amar perdona.",
            "Il cielo in una stanza, quando sei qui con me.",
            "Sapore di sale, sapore di mare.",
            "Non è Francesca, lei non è qui.",
            "Disperato erotico stomp.",
            "Com'è profondo il mare.",
            "Futura, aspettiamo che ritorni la luce.",
            "4 marzo 1943, diceva di essere mia madre.",
            "L'italiano, lasciatemi cantare un po'.",
            "Un'emozione da poco, ma cresce dentro me.",
            "Tanta voglia di lei, e non riesco a fermarmi.",
            "Pensiero, non lasciarmi solo.",
            "Chi fermerà la musica, se non noi?",
            "Uomini soli, persi nella notte.",
            "Piccola Katy, vieni qui vicino.",
            "Io vagabondo che non sono altro.",
            "Dio è morto, nei campi di concentramento.",
            "Canzone per un'amica, che non c'è più.",
            "Versò il vino e spezzò il pane.",
            "Ciao amore, ciao amore, ciao amore ciao.",
            "Vedrai vedrai, vedrai che cambierà.",
            "Ho capito che ti amo, quando ho visto che bastava.",
            "Lontano lontano, nel tempo e nello spazio.",
            "Senza fine, per te io darei tutto.",
            "Il nostro concerto, suona per noi.",
            "Arrivederci, Roma, goodbye, au revoir.",
            "Ciao ciao bambina, un bacio ancora.",
            "Piove, il pineto è solo.",
            "Meraviglioso, ma come non ti accorgi di quanto il mondo sia meraviglioso?",
            "L'appuntamento, ho fatto un terno al lotto.",
            "Una ragione di più, per restare insieme.",
            "Domani è un altro giorno, si vedrà.",
            "Minuetto, danza con me ancora una volta.",
            "Almeno tu nell'universo, un punto fermo per me.",
            "Piccola stella senza cielo, ti mostrerò io la strada.",
            "Certe notti la macchina è calda.",
            "Urlando contro il cielo, scateniamo la tempesta.",
            "Ho messo via un po' di consigli.",
            "Non è tempo per noi, e forse non lo sarà mai.",
            "A che ora è la fine del mondo?",
            "Ehi fratellino, come va?",
            "Il mio nome è mai più, gridiamo tutti insieme.",
            "Vivere, e sorridere dei guai.",
            "Liberi liberi siamo noi.",
            "Ogni volta che viene giorno.",
            "T'innamorerai, quando meno te lo aspetti.",
            "Bella stronza, che mi hai spezzato il cuore.",
            "Disperato, senza direzione.",
            "Ci vorrebbe il mare, per lavare le ferite.",
            "Ricordati di me, quando il sole sorge.",
            "Roma capoccia, der mondo infame.",
            "Sotto il segno dei pesci, siamo nati noi.",
            "Amici mai, per chi si cerca come noi.",
            "Che fantastica storia è la vita.",
            "In questo mondo di ladri, c'è ancora un po' d'amore.",
            "Ci vorrebbe un amico, per dimenticare il male.",
            "Top!",
            "Che hit!",
            "Bff",
            "Spaccare",
            "Questa roba spacca!",
            "Brocco",
            "Ghostare",
            "Friendzonato",
            "Crush",
            "Ho una crush per lei.",
            "Cringeissimo",
            "Che trash!",
            "Swag",
            "Raga",
            "Bella fra!",
            "Non ci sta.",
            "Che bomba!",
            "Zarro / Tamarro",
            "Pomiciare",
            "Baccaglie",
            "Sbroccare",
            "Sclerare",
            "Sto sclerando!",
            "A palla!",
            "Musica a palla!",
            "Stai rosicando?",
            "Sbronza",
            "Ho una sbronza terribile.",
            "Dai!",
            "Ma va!",
            "Figo!",
            "Che figata!",
            "Che sbatti!",
            "Mamma mia!",
            "Accidenti!",
            "Cavolo!",
            "Caspiterina!",
            "Magari!",
            "Basta!",
            "Meno male!",
            "Pensa te!",
            "Manco per sogno!",
            "Macché!",
            "Ma figurati!",
            "Tanta roba!",
            "Madonna!",
            "Pazzesco!",
            "Sei un mito!",
            "Ci sono!",
            "Non me ne frega niente.",
            "Me ne frego!",
            "Fare la figura del pollo.",
            "Sei fuori!",
            "Fuori di testa!",
            "Mantieni la calma.",
            "Mollami!",
            "Lasciami in pace.",
            "Che pesante!",
            "Non rompere le scatole!",
            "Ammore!",
            "Tesoro",
            "Sei carino/a.",
            "Mi fai impazzire.",
            "Limonare",
            "Stare insieme",
            "Fare serata",
            "Andiamo a fare aperitivo.",
            "Sbocciare",
            "Fare baldoria",
            "Che calura!",
            "Offri tu?",
            "Sto a un passo dal baratro.",
            "Sono a pezzi.",
            "Ho un sonno cane.",
            "In bocca al lupo!",
            "Crepi!",
            "Tocca a te.",
            "Fai con calma.",
            "Tutto a posto?",
            "Bella zio!",
            "Fatturato",
            "Avoja!",
            "Anco'",
            "Che ti po' possino!",
            "Uagliò!",
            "Jammo ja'!",
            "Statte zitto!",
            "Maronn'!",
            "Che Sfiga!",
            "Sfigato",
            "Mah!",
            "Beh?",
            "Eh già!",
            "A posto!",
            "Perfetto!",
            "Tutto chiaro?",
            "Main character energy",
            "NPC",
            "Pov",
            "Sei un NPC!",
            "Fare il brillante",
            "Fare il finto tonto",
            "Non fare il furbo!",
            "Te la tiri!",
            "Se la tira troppo.",
            "Che rosicata!",
            "Sei un rosicone.",
            "Gatta ci cova.",
            "Cadere dalle nuvole",
            "Avere la puzza sotto il naso",
            "Parlare a vanvera",
            "Non dire cavolate!",
            "Senza parole.",
            "Restare di sasso",
            "Chi se ne importa!",
            "Fattela passata!",
            "Pensa per te!",
            "Fate vobis.",
            "Come vuoi.",
            "Fai pure.",
            "Non c'è storia.",
            "C'è poco da fare.",
            "Punto e basta.",
            "O la va o la spacca!",
            "Chi vivrà vedrà.",
            "Col cavolo!",
            "Neanche per idea!",
            "Sogni d'oro!",
            "Tieniti forte!",
            "Prendere due piccioni con una fava.",
            "Piove sul bagnato.",
            "Tutto è bene quel che finisce bene.",
            "Chi dorme non piglia pesci.",
            "Avanti!",
            "Andiamo!",
            "Vabbè!",
            "Vabbè dai.",
            "Ho capito.",
            "Capito niente.",
            "Ci sta tutta.",
            "Manco morto!",
            "Assolutamente sì!",
            "Assolutamente no!",
            "Cosa c'è?",
            "Che c'è che non va?",
            "Arrivo!",
            "Sono in ritardo!",
            "Che caos!",
            "Un casino!",
            "Ho fatto un casino.",
            "Che macello!",
            "Stai scherzando?",
            "Dici sul serio?",
            "Davvero?",
            "Ma ti pare?",
            "Senza dubbio.",
            "Ti giuro!",
            "Giuro su mia madre!",
            "Manco io.",
            "Anch'io!",
            "Ci sentiamo!",
            "Fatti sentire!",
            "Ci becchiamo in giro!",
            "Bacioni!",
            "Un abbraccio!",
            "Buona vita!",
            "Ciao caro/a!",
    };

    public SemanticMatcherIt(Context context) {
        super(context, TAG, ASSET_PATH, FALLBACK_QUESTIONS, randomActions());
    }

    /** fallback 動作全部 __RANDOM__：幾多答句就幾多個位，SemanticCenter
     *  見到呢個標記會即場隨機選動作 (見 ActionDirect.resolveRandomActionId())。 */
    private static String[] randomActions() {
        String[] a = new String[FALLBACK_QUESTIONS.length];
        for (int i = 0; i < a.length; i++) {
            a[i] = "__RANDOM__";
        }
        return a;
    }
}
