package com.open.alpha2;

import android.content.Context;

/**
 * 西班牙文語意配對引擎 - 和 SemanticMatcherZh (中文版)／SemanticMatcherEn
 * (英文版) 同一套語意配對機制, 專門處理西班牙文。
 *
 * 資料來源: assets/semantic/semantic_es.json (v2 grouped 格式, 同中英文版同一個
 * schema - 見 SemanticMatcherBase.load())。85 ACTION (同其他語言同 op/actionId)
 * ＋200 日常 CHAT (es.daily.001-200，每組 5 問法＋口語答案 5 句，生活話題，
 * 中性西語 tuteo，日版覆盖為參照)。每個 intent 內:
 *   qs       - 用戶問法 (例如 "Hola", "Fiesta", "Háblame de amor")
 *   a        - 候選答案句 (隨機選一句做 TTS)
 *   type     - 全部 CHAT（第一版唔接動作，全部用已驗證 silent filler action id）
 *   actionId - filler 動作 id（思考／開心／贊同等silent 動作，同 TTS 一齊播唔打架；
 *              有聲判斷照行 SemanticCenter／ActionDirect.isSoundAction() 同一套）。
 *
 * 這個 class 只負責「文字 -> 配對結果」, 不負責執行 TTS/動作 - 跟著這個 project
 * 一貫的分層方式，執行那一步留給呼叫方 (SemanticCenter 的 handleSemanticMatch)
 * 做, 方便測試和重用。
 *
 * 只做西班牙文 - 和中英文版各自獨立, 沒在這個 class 裡加 language 參數
 * (因為機身 ASR 引擎本身一次只能選到一種語言, matcher 不會同時用）。
 * SemanticCenter.handleSemanticMatch() 根據對話語言／文字判斷結果, 選用哪一個。
 * 載入/比對/分類 random 的實際邏輯全部在 SemanticMatcherBase, 這裡只提供
 * 西班牙文專屬的 TAG/assets 路徑/fallback 問法組。
 *
 * Zero-third-party-dependency: 只用 org.json (Android 內建, 經 base class), 沒額外
 * library。
 */
public class SemanticMatcherEs extends SemanticMatcherBase {
    private static final String TAG = "SemanticMatcherEs";
    private static final String ASSET_PATH = "semantic/semantic_es.json";

    /** fallback 答句池 - spanish800.txt 用剩的未配對句全數搬過嚟 (generated, 唔好手改；
     *  要加減句請改 spanish_raw_lines.json + semantic_es.json 配對結果再 rerun；
     *  粗口/性暗示/貶損類俚語已剔除，唔入池)。
     *  聽唔明就隨機噏一句，動作全部 __RANDOM__ (SemanticCenter 見到會即場由隨機
     *  filler 池 60 個裡面選一個)，次次唔同 - 同中日版的 fallback 做法一致。 */
    private static final String[] FALLBACK_QUESTIONS = {
            "La vida no es lo que uno vivió, sino la que uno recuerda para contarla.",
            "A veces la verdad es tan increíble que la mentira suena más convincente.",
            "No hay nada más peligroso que un hombre sin nada que perder.",
            "Todos tenemos un precio, solo hay que saber cuál es.",
            "Un secreto deja de serlo cuando dos personas lo saben.",
            "El destino es una excusa para los que no tienen agallas.",
            "A veces hay que romper las reglas para hacer lo correcto.",
            "No confíes en nadie que no tenga nada que ocultar.",
            "Las mejores decisiones se toman con el corazón caliente y la cabeza fría.",
            "El tiempo cura todo, menos la verdad.",
            "Para sobrevivir aquí, tienes que aprender a no sentir nada.",
            "A veces el monstruo no está debajo de la cama, está dentro de ti.",
            "La lealtad no se compra, se demuestra.",
            "Hay errores que se pagan toda la vida.",
            "La libertad cuesta más de lo que cualquiera está dispuesto a pagar.",
            "No somos lo que decimos, somos lo que hacemos.",
            "Te amé desde el primer instante en que te vi.",
            "No me pidas que te olvide cuando eres lo único que recuerdo.",
            "El amor verdader no busca un final feliz, porque no tiene fin.",
            "Prefiero un día contigo que mil años sin ti.",
            "Si me olvides, no te culpo; si me recuerdas, te lo agradeceré.",
            "Tú eres mi principio y mi fin.",
            "No hay distancia capaz de apagar este fuego.",
            "Me enamoré de tu sombra antes de conocer tu luz.",
            "El amor es una locura de la que nadie quiere curarse.",
            "Eres el único error que volvería a cometer mil veces.",
            "A veces amarse no es suficiente.",
            "Mi corazón dejó de ser mío el día que te conocí.",
            "No te quiero por lo que eres, sino por lo que soy cuando estoy contigo.",
            "Prométeme que nunca olvidarás este momento.",
            "El dolor de perderte es el precio de haberte amado.",
            "Siento que te he buscado durante varias vidas.",
            "Tú me enseñaste a sentir cosas que ni sabía que existían.",
            "El amor no se entiende, se vive.",
            "Quédate conmigo, aunque todo el mundo se oponga.",
            "Baja el arma o esto va a terminar muy mal.",
            "No vine a negociar, vine a cobrar.",
            "Si das un paso más, será el último.",
            "¿Vas a disparar o vas a seguir hablando?",
            "No sabes con quién te estás metiendo.",
            "Esto no se acaba hasta que yo lo diga.",
            "Me quitas algo y te quitaré todo.",
            "El tiempo se te está acabando.",
            "La venganza es el único idioma que entiendes.",
            "Nunca olvides quién manda aquí.",
            "Hazlo rápido o lo haré yo por ti.",
            "Todo el mundo tiene un punto débil.",
            "No me amenaces si no estás dispuesto a cumplirlo.",
            "Te dije que este día llegaría.",
            "No hay escapatoria para lo que hiciste.",
            "Nadie sale de aquí sin pagar su deuda.",
            "Tus palabras no me asustan, tus actos me divierten.",
            "Solo uno de nosotros saldrá caminando de aquí.",
            "Se te acabó la suerte.",
            "Nada ocurre por casualidad en este negocio.",
            "El crimen perfecto no existe, solo los investigadores mediocres.",
            "Si quieres encontrar la verdad, sigue el dinero.",
            "Todos son culpables hasta que se demuestre lo contrario.",
            "La sombra más oscura es la que proyecta la luz más brillante.",
            "No hay huellas cuando la mente es la que mata.",
            "El asesino siempre vuelve al lugar del crimen.",
            "La codicia cegó a hombres más inteligentes que tú.",
            "Cree solo en la mitad de lo que veas y en nada de lo que oigas.",
            "Detrás de cada gran fortuna hay un gran delito.",
            "A veces la mejor escondite es a la vista de todos.",
            "No hay nada más peligroso que un aliado desesperado.",
            "Tu silencio es la prueba que estaba buscando.",
            "En este juego, la piedad se paga con la muerte.",
            "Cuidado con lo que deseas, podrías conseguirlo.",
            "Hay una línea muy fina entre la obsesión y la locura.",
            "El pasado te persigue sin importar cuán rápido corras.",
            "Todo inocente tiene un lado oscuro.",
            "La sospecha es una semilla que nunca deja de crecer.",
            "Nos convertimos en las personas que juramos nunca ser.",
            "La soledad es el precio de la libertad.",
            "El orgullo destruye más vidas que la peste.",
            "A veces la única forma de salvarse es perderlo todo.",
            "Aprende a renunciar a lo que no puedes cambiar.",
            "La ignorancia es una bendición para el que no quiere ver.",
            "No hay mayor prisión que la mente de uno mismo.",
            "Nos pasamos la vida esperando el momento perfecto, y la vida se va.",
            "La verdad nos hará libres, pero primero nos destruirá.",
            "No juzgues una historia si no conoces todo el libro.",
            "El alma que se vende una vez no se vuelve a recuperar.",
            "Las cicatrices son los mapas de nuestras batallas.",
            "El poder no cambia a las personas, solo las al des desnudo.",
            "Hay cosas que el dinero no puede comprar, como una conciencia limpia.",
            "El tiempo nos vuelve sabios o nos vuelve amargados.",
            "La esperanza es lo último que se pierde, pero a veces es lo que más duele.",
            "Nadie conoce a nadie realmente.",
            "Somos el resultado de nuestras propias decisiones.",
            "Al final, solo nos queda lo que dimos a los demás.",
            "No hay tiempo para lamentaciones.",
            "Déjame en paz de una vez por todas.",
            "¿Estás loco o qué te pasa?",
            "Eso no te incumbe a ti.",
            "No tengo nada más que decirte.",
            "Es ahora o nunca.",
            "No te rindas tan fácilmente.",
            "Confía en mí, sé lo que hago.",
            "Te lo dije y no me escuchaste.",
            "Todo va a salir bien, te lo prometo.",
            "No te metas donde no te llaman.",
            "Olvídalo, no vale la pena.",
            "¿De qué estás hablando?",
            "Eso es imposible de creer.",
            "Ten cuidado con lo que dices.",
            "No me falles esta vez.",
            "No tienes la menor idea.",
            "El silencio a veces dice más que las palabras.",
            "No me juzgues sin conocerme.",
            "Quédate con la duda si quieres.",
            "Acepta las cosas como son.",
            "No hay nada que podamos hacer al respecto.",
            "Me decepcionaste cuando más te necesitaba.",
            "Nada cambia si tú no cambias.",
            "A veces el camino más difícil es el correcto.",
            "No puedo prometerte nada.",
            "Lo hecho, hecho está.",
            "Es más complicado de lo que piensas.",
            "Ese es el menor de nuestros problemas.",
            "Nadie puede cambiar el pasado.",
            "Mantén a tus amigos cerca, pero a tus enemigos más cerca.",
            "No tenemos toda la noche.",
            "Si no me ayudas, estás en mi contra.",
            "Llegas tarde como siempre.",
            "Eso suena demasiado bueno para ser verdad.",
            "Aprende de tus errores.",
            "No te dejes llevar por la ira.",
            "No sabes cuánto me costó llegar hasta aquí.",
            "Siento haber dudado de ti.",
            "Nunca es tarde para empezar de nuevo.",
            "La verdad siempre sale a la luz.",
            "No dejes para mañana lo que puedes hacer hoy.",
            "Me estás ocultando algo.",
            "El mundo no gira a tu alrededor.",
            "Esa es una decisión que debes tomar tú.",
            "No me pidas imposibles.",
            "Vale la pena intentar una vez más.",
            "Tu vida está a punto de cambiar.",
            "Es el precio que hay que pagar por el éxito.",
            "Las palabras se las lleva el viento.",
            "No me des explicaciones, dame resultados.",
            "¿Qué harías tú en mi lugar?",
            "No hay motivo para alarmarse.",
            "Te debo una muy grande.",
            "Todo fue una trampa desde el principio.",
            "No me hagas perder el tiempo.",
            "Afronta la realidad de una vez.",
            "Nada de esto tendría que haber pasado.",
            "No escuches lo que dicen los demás.",
            "Ese no es el camino correcto.",
            "Mis intenciones eran buenas.",
            "Nadie te obligó a hacer esto.",
            "El dinero no compra la felicidad, pero ayuda bastante.",
            "No me mires así.",
            "Hay cosas que prefiero no saber.",
            "No nos queda otra opción.",
            "Tienes que aprender a escuchar.",
            "Esa historia ya me la conozco.",
            "No pongas excusas.",
            "Si vas a hacerlo, hazlo bien.",
            "Te lo mereces por todo lo que hiciste.",
            "Siempre hay una primera vez.",
            "No juegues con mi paciencia.",
            "No me arrepiento de nada.",
            "El silencio fue su mejor respuesta.",
            "No puedo cambiar quien soy.",
            "Todo tiene un límite.",
            "Es el principio del fin.",
            "Mantén la cabeza en alto.",
            "A veces hay que perder para ganar.",
            "No me pidas que cambie mi forma de pensar.",
            "Esa es la diferencia entre tú y yo.",
            "Todo tiene su momento y su lugar.",
            "No dejes que el miedo decida por ti.",
            "El espectáculo debe continuar.",
            "Despacito, quiero respirar tu cuello despacito.",
            "Pasito a pasito, suave suavecito, nos vamos pegando poquito a poquito.",
            "Bailando, bailando, tu cuerpo con el mío llenando el vacío.",
            "La vida es un carnaval, y las penas se van cantando.",
            "Dale a tu cuerpo alegría Macarena, que tu cuerpo es pa' darle alegría y cosa buena.",
            "A ella le gusta la gasolina, dame más gasolina.",
            "Hoy se sale a la calle a celebrar el amor y la libertad.",
            "Suéltate el pelo y ponte a bailar.",
            "Mueve las caderas al ritmo del tambor.",
            "Todos juntos cantando bajo las estrellas.",
            "Bésame, bésame mucho, como si fuera esta noche la última vez.",
            "Eres el amor de mi vida, el aire que respiro.",
            "Contigo aprendí que existen nuevas y mejores emociones.",
            "Tu sonrisa es la luz que ilumina mi camino oscuro.",
            "Solamente tú haces que mi mundo gire con sentido.",
            "Si no te tuviera, no sabría cómo vivir.",
            "Te quiero no por quien eres, sino por como me haces sentir.",
            "Cada segundo a tu lado es un regalo del cielo.",
            "Estar contigo es tocar el cielo con las manos.",
            "Quiero perderme en tu mirada toda la noche.",
            "A tu lado me siento invencible.",
            "Eres mi sueño hecho realidad.",
            "No necesito nada más si te tengo a ti.",
            "Tus besos son el dulce veneno que me domina.",
            "Amor del bueno, del que nunca se acaba.",
            "Mi lugar favorito en el mundo es a tu lado.",
            "En tus brazos encontré la paz que tanto buscaba.",
            "Amo cada detalle de tu persona.",
            "¿Quién me va a curar el corazón partío?",
            "Como la flor, con tanto amor, me diste tú, se marchitó.",
            "Y se marchó, y a su barco le llamó Libertad.",
            "Fue un placer conocerte, aunque me haya dolido el final.",
            "Hoy me faltan las palabras para explicar tanto dolor.",
            "Prefiero estar solo que estar mal acompañado.",
            "Te fuiste sin decir adiós y me dejaste en ruinas.",
            "El tiempo no borra los recuerdos de lo que fuimos.",
            "Duele saber que ya no piensas en mí.",
            "Prometiste estar conmigo y me abandonaste.",
            "Trato de olvidarte pero te encuentro en todas partes.",
            "Lágrimas que caen en la soledad de mi habitación.",
            "Mi corazón se congeló el día que te alejaste.",
            "Aprendí a vivir con tu ausencia, pero no a dejar de extrañarte.",
            "No me quedan lágrimas para llorar por ti.",
            "Eras mi todo y ahora eres solo un desconocido.",
            "El silencio de esta casa me hace recordar tu voz.",
            "Guardé todas tus cartas pero quemé las promesas.",
            "Nada vuelve a ser igual después de una traición.",
            "Te entregué mi vida y solo me dejaste cicatrices.",
            "Saber que se puede, querer que se pueda, quitarse los miedos, sacarlos afuera.",
            "A Dios le pido que si me muero sea de amor y si me enamoro sea de ti.",
            "Color esperanza, pintarse la cara color esperanza.",
            "Canta y no llores, porque cantando se alegran los corazones.",
            "Caminante, no hay camino, se hace camino al andar.",
            "Gracias a la vida que me ha dado tanto.",
            "Las heridas sanan pero las lecciones se quedan.",
            "Sigue tus sueños sin importar lo que digan.",
            "La fe mueve montañas y cambia destinos.",
            "Aprende a caer para saber cómo levantarte.",
            "Sé la luz que ilumine la oscuridad de otros.",
            "Lucha por lo que amas sin mirar atrás.",
            "Un mundo mejor es posible si lo construimos juntos.",
            "México lindo y querido, si muero lejos de ti...",
            "Tierra de mis amores, donde nacieron mis recuerdos.",
            "Orgullo de mis raíces y mi gente.",
            "Llevo el ritmo de mi pueblo en la sangre.",
            "Cantándole a la luna y a las estrellas del mar.",
            "Hispano de corazón, cantando al mundo mi verdad.",
            "Las guitarras suenan y el alma se despierta.",
            "Mami, tú sabes que me gustas demasiado.",
            "Ella camina con estilo y todos la miran pasar.",
            "No hay tiempo para rodeos, dímelo ya.",
            "Esta noche somos tú y yo contra el mundo.",
            "No me importa el mañana, solo disfruto el hoy.",
            "Una mirada tuya basta para volverme loco.",
            "Dame una razón más para no soltarte.",
            "Luces de la ciudad encendidas para los dos.",
            "Un beso bajo la lluvia que nunca olvidaré.",
            "Te llevo tatuado en el pensamiento.",
            "Mi amor por ti es más profundo que el océano.",
            "No hay barreras para el amor verdadero.",
            "El tiempo pasa volando cuando estoy contigo.",
            "Quiero ser el refugio donde te sientas seguro.",
            "Tu amor es el faro que me guía en la tormenta.",
            "Se acabaron las mentiras, hoy empieza la verdad.",
            "A pesar del tiempo, sigo esperándote.",
            "No me prometas el cielo, solo dame tu presencia.",
            "Un suspiro tuyo vale más que mil palabras.",
            "Gritemos al mundo lo que sentimos.",
            "Somos dos almas conectadas por la música.",
            "Nada de lo que vivimos fue en vano.",
            "Cierra los ojos y siente la magia.",
            "El destino nos unió por una razón.",
            "Tus besos me transportan a otro universo.",
            "No hay nada de malo en querer un poco más.",
            "Sigue la melodía de tu propio corazón.",
            "A veces la distancia nos enseña a valorar.",
            "Tu recuerdo me persigue en cada rincón.",
            "Hoy brindo por los que ya no están.",
            "El fuego de la pasión nunca se apaga.",
            "Tú y yo nacimos para estar juntos.",
            "El silencio entre nosotros lo dice todo.",
            "Voy a cantar mi historia sin importar la opinión.",
            "Vive hoy como si fuera el último día.",
            "El arte de amar sin pedir nada a cambio.",
            "Siento que vuelo cuando rozas mi piel.",
            "La noche promete sorpresas e inolvidables momentos.",
            "Con un abrazo tuyo el mundo se detiene.",
            "Tu nombre está grabado en mi memoria.",
            "El amanecer nos encontrará juntos bailando.",
            "Abre las alas y vuela tan alto como puedas.",
            "El amor no tiene edad ni fronteras.",
            "Me pierdo en la profundidad de tus ojos negros.",
            "Aprender a soltar es también una forma de amar.",
            "Cada acorde despierta un sentimiento guardado.",
            "No necesito riquezas, solo tu compañía.",
            "Tus palabras me llenan de esperanza.",
            "Que el amor sea nuestro único lenguaje.",
            "Estar a tu lado es mi refugio perfecto.",
            "No dejes que la rutina apague nuestra llama.",
            "Sé la mejor versión de ti mismo hoy.",
            "Tu sonrisa vale más que todo el oro del mundo.",
            "Caminemos juntos por el camino de la vida.",
            "El recuerdo de tu voz me da fuerzas.",
            "No hay noche tan oscura que impida el amanecer.",
            "El tiempo que pasamos juntos nunca es perdido.",
            "Eres mi estrella fugaz, la que pide mis deseos.",
            "Suéltate y déjate amar.",
            "Tu perfume quedó grabado en mi almohada.",
            "Eres la razón por la que canto cada mañana.",
            "Siento que toque las estrellas cuando te besé.",
            "Nadie nos enseñó a amar, aprendimos juntos.",
            "Un amor como el nuestro superará cualquier prueba.",
            "El mundo necesita más amor y menos odio.",
            "Eres mi refugio en los días grises.",
            "No hay distancia que enfríe este amor.",
            "Un abrazo tuyo cura cualquier dolor.",
            "La vida es un suspiro, disfrútalo al máximo.",
            "Tu amor es el tesoro más grande que poseo.",
            "Aprende a valorar las pequeñas cosas de la vida.",
            "La belleza interior es la que nunca se marchita.",
            "Tus abrazos son mi lugar seguro.",
            "El destino decide quién entra en tu vida, tú decides quién se queda.",
            "Que tus sueños sean más grandes que tus miedos.",
            "Un poema cantado directo al corazón.",
            "Sigue la luz que llevas dentro.",
            "El verdadero amor aguanta el paso del tiempo.",
            "Hoy bailo por los que ya no están aquí.",
            "Canta sin parar hasta que el cuerpo agante.",
            "El arte es la mentira que nos permite comprender la verdad.",
            "Aprende las reglas como un profesional para poder romperlas como un artista.",
            "Pinto autorretratos porque estoy mucho tiempo sola, porque soy la persona que mejor conozco.",
            "Pies, para qué los quiero si tengo alas pa' volar.",
            "En la vida no hay premios ni castigos, sino consecuencias.",
            "Que no sepas que estás en la gloria, no significa que no estés en ella.",
            "La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos.",
            "El que lee mucho y anda mucho, ve mucho y sabe mucho.",
            "Uno es dueño de lo que calla y esclavo de lo que habla.",
            "Hay que sentir la vida, no comprenderla.",
            "El amor es una emoción que te enloquece y luego te devuelve la cordura.",
            "La memoria del corazón elimina los malos recuerdos y magnifica los buenos.",
            "Ninguna persona merece tus lágrimas, y quien la merezca no te hará llorar.",
            "La vida no es la que uno vivió, sino la que uno recuerda.",
            "Para hacer el bien, hay que conocerlo primero.",
            "El éxito no es el final, el fracaso no es fatal: es el valor para continuar lo que cuenta.",
            "Si no crees en ti mismo, nadie más lo hará.",
            "El éxito es aprender a ir de fracaso en fracaso sin perder el entusiasmo.",
            "Tienes que luchar para alcanzar tus sueños, hay que sacrificarse.",
            "Prefiero ser buena persona a ser el mejor jugador del mundo.",
            "Tu amor me hace fuerte, tu odio me hace imparable.",
            "No quiero ser igual a los demás, quiero ser único.",
            "El trabajo duro supera al talento cuando el talento no trabaja duro.",
            "La velocidad no sirve de nada si no sabes hacia dónde vas.",
            "No hay nada imposible, solo hay cosas más difíciles que otras.",
            "La pasión es el único motor del éxito a largo plazo.",
            "El fracaso no es el fin, es solo el comienzo de algo mejor.",
            "Acepta quien eres y conviértelo en tu mayor fortaleza.",
            "El respeto se gana, no se pide ni se exige.",
            "Haz lo que amas y nunca trabajarás un solo día de tu vida.",
            "Aprende a amar tus imperfecciones, son las que te hacen único.",
            "La humildad debe ser siempre tu mayor virtud.",
            "Si puedes soñarlo, puedes lograrlo con trabajo y disciplina.",
            "La disciplina es el puente entre las metas y los logros.",
            "No cuentes los días, haz que los días cuenten.",
            "La mayor gloria no es no caer nunca, sino levantarse siempre.",
            "Lo único imposible es aquello que no intentas.",
            "Crea tu propio camino y deja una huella.",
            "El momento perfecto es hoy, no esperes al mañana.",
            "Sé la versión original de ti mismo, no una copia.",
            "La actitud es una pequeña cosa que hace una gran diferencia.",
            "Las grandes mentes discuten ideas, las mentes promedio discuten eventos.",
            "El conocimiento es poder, pero la sabiduría es libertad.",
            "El único límite a nuestros logros es nuestra propia mente.",
            "No esperes oportunidades, créalas tú mismo.",
            "Haz de tu vida una obra de arte.",
            "El perdón no cambia el pasado, pero expande el futuro.",
            "Lo que no nos mata nos hace más fuertes.",
            "La verdadera felicidad viene de servir a los demás.",
            "Tu tiempo es limitado, no lo malgastes viviendo la vida de otro.",
            "El cambio empieza cuando decides tomar el control.",
            "Un hombre sabio habla porque tiene algo que decir; un necio porque tiene que decir algo.",
            "Supera tus miedos para descubrir tu verdadero potencial.",
            "Nunca es tarde para ser lo que podrías haber sido.",
            "Aprende a sonreír incluso en medio de la tormenta.",
            "El alma noble siempre encuentra el camino hacia el bien.",
            "La perseverancia es la clave que abre todas las puertas.",
            "Haz todo con pasión o no lo hagas.",
            "No te conformes con menos de lo que mereces.",
            "A veces hay que perderse para encontrarse a uno mismo.",
            "La mente abierta es la puerta al crecimiento personal.",
            "Vive con propósito y muere sin arrepentimientos.",
            "Siembra buena semilla hoy para cosechar buenos frutos mañana.",
            "La generosidad no consiste en dar mucho, sino en dar a tiempo.",
            "No dejes que el ruido exterior apague tu voz interior.",
            "Ama lo que haces y el éxito te seguirá de forma natural.",
            "Sigue tus ideales sin importar las dificultades.",
            "El éxito no es cuestión de suerte, es cuestión de elección.",
            "La paciencia es la virtud de los fuertes.",
            "Cree en el proceso y confía en tu intuición.",
            "Tus pensamientos crean tu realidad.",
            "Aprende del dolor para convertirlo en sabiduría.",
            "No prometas cuando estés feliz, no respondas cuando estés enojado.",
            "Haz el bien sin mirar a quién.",
            "Quien tiene un porqué para vivir puede soportar casi cualquier cómo.",
            "El destino no es una cuestión de casualidad, sino de elección.",
            "El amor propio es el comienzo de un romance de por vida.",
            "Sé tú mismo, los demás puestos ya están ocupados.",
            "Todo lo que puedes imaginar es real.",
            "La verdad es el camino más directo hacia la libertad.",
            "Donde hay voluntad, hay un camino.",
            "La paciencia es amarga, pero sus frutos son dulces.",
            "No dejes que los pequeños detalles arruinen tus grandes planes.",
            "El coraje es saber a qué no hay que tenerle miedo.",
            "Quien busca la perfección termina no haciendo nada.",
            "La verdadera belleza es invisible a los ojos.",
            "El tiempo es el único recurso que jamás se recupera.",
            "La empatía es la clave para conectar con los demás.",
            "No hay barrera que pueda contener la determinación humana.",
            "La felicidad depende de nosotros mismos.",
            "Aprender a escuchar es tan importante como aprender a hablar.",
            "No vivas para complacer a los demás, vive para ser auténtico.",
            "Cada error superado es un paso más cerca de la meta.",
            "Mantén tus ideales firmes ante las tempestades.",
            "El carácter de una persona se demuestra en momentos difíciles.",
            "No midas tu éxito por el dinero, sino por la paz mental.",
            "El conocimiento no ocupa lugar pero abre infinitas puertas.",
            "Acepta los cambios con los brazos abiertos.",
            "La vida es un regalo, vívela al máximo.",
            "La perseverancia vence lo que la dicha no alcanza.",
            "Sé amable con todos los que encuentres en tu camino.",
            "La sabiduría empieza en la reflexión.",
            "No mires atrás a menos que sea para aprender del pasado.",
            "Tu fe debe ser más grande que tus temores.",
            "Quien tiene paz interior lo tiene todo.",
            "El alma se alimenta de bellos momentos.",
            "No hay caminante sin camino, ni historia sin destino.",
            "La paciencia y el tiempo hacen más que la fuerza.",
            "Lucha por tus principios sin importar las consecuencias.",
            "La humildad nos hace grandes ante los demás.",
            "Nunca renuncies a lo que realmente deseas.",
            "El camino a la grandeza requiere sacrificio.",
            "El trabajo honesto siempre rinde frutos.",
            "Aprende a perdonarte a ti mismo antes que a los demás.",
            "Las acciones hablan más fuerte que las palabras.",
            "El verdadero valor reside en decir la verdad.",
            "Sé la luz en medio de la oscuridad de alguien.",
            "El éxito dura un instante, el aprendizaje toda la vida.",
            "No hay atajos para los lugares a los que vale la pena ir.",
            "Tu actitud determina tu altitud.",
            "La vida es corta, haz que valga la pena.",
            "El respeto es la base de la convivencia pacífica.",
            "Aprende de todos, no te creas superior a nadie.",
            "La sinceridad es un regalo caro, no la esperes de gente barata.",
            "El cambio es inevitable, el crecimiento es opcional.",
            "Haz lo correcto aunque nadie te esté mirando.",
            "Sigue tus pasiones y el universo abrirá puertas donde solo había muros.",
            "No hay triunfo sin esfuerzo previo.",
            "Acepta las críticas constructivas con humildad.",
            "Sé generoso con tu tiempo y con tus palabras de aliento.",
            "El pasado ya se fue, el futuro no ha llegado, vive el presente.",
            "La verdad nos da la libertad de ser nosotros mismos.",
            "No busques la aprobación de los demás, busca la tuya propia.",
            "Desarrolla una mente fuerte para enfrentar los desafíos.",
            "La libertad consiste en ser dueño de la propia vida.",
            "Sé constante en tus esfuerzos y paciente con tus resultados.",
            "La bondad siempre deja una huella imborrable.",
            "Afronta las adversidades con valentía y optimismo.",
            "No dejes que las circunstancias dicten tu felicidad.",
            "El arte de amar es también el arte de respetar.",
            "Siembra pensamientos positivos y cosecharás éxito.",
            "La verdad florece tarde o temprano.",
            "Sé fiel a tus valores en todo momento.",
            "El tiempo libre es la mejor fortuna para el sabio.",
            "No hay nada de malo en admitir un error.",
            "Aprende a adaptarte a los cambios de la vida.",
            "La fe mueve fronteras y rompe barreras.",
            "Sé un ejemplo positivo para las futuras generaciones.",
            "La perseverancia convierte lo imposible en realidad.",
            "Aprecia las bendiciones diarias que recibes.",
            "El futuro pertenece a quienes creen en la belleza de sus sueños.",
            "Nada grande se ha conseguido sin entusiasmo.",
            "La mente es como un paracaídas: solo funciona si se abre.",
            "Sé promotor de paz allá donde vayas.",
            "El trabajo en equipo divide las tareas y multiplica el éxito.",
            "Aprende a decir no cuando sea necesario.",
            "La sinceridad conduce a relaciones verdaderas y duraderas.",
            "Supera el miedo al fracaso y alcanzarás la gloria.",
            "Vive el presente con plenitud y alegría.",
            "Tu destino está en tus propias manos.",
            "Aprende a transformar los problemas en oportunidades de aprendizaje.",
            "La verdadera elegancia está en la sencillez y la educación.",
            "Sé el cambio que deseas ver en el mundo.",
            "La fuerza de voluntad es el motor del alma.",
            "No dejes que las opiniones ajenas definan tu valor.",
            "El amor verdadero trasciende el espacio y el tiempo.",
            "Siembra amor y cosecharás paz interior.",
            "La vida es una constante aventura de aprendizaje.",
            "El esfuerzo de hoy es la recompensa del mañana.",
            "Sé libre de prejuicios y abierto al mundo.",
            "La verdad nos fortalece ante las tormentas.",
            "Al final, el amor es lo único que prevalece.",
            "¡Mola mucho!",
            "¿Qué pasa, tío/tía?",
            "Es una pasada.",
            "Estar como una cabra.",
            "No me comas la cabeza.",
            "Estar en la parra.",
            "¡Qué fuerte!",
            "Ser un fantasma.",
            "Estar de buen rollo.",
            "¡Ostras!» / «¡Jolín!",
            "Estar petado.",
            "Me importa un pimiento.",
            "Currar",
            "Pasta",
            "Dar la lata.",
            "Liarla parda.",
            "Ser la leche.",
            "Tener un cacao en la cabeza.",
            "Ir al grano.",
            "Ponerse las pilas.",
            "Hacer una chapuza.",
            "Tomar el pelo.",
            "Estar a dos velas.",
            "Montar un pollo.",
            "Tirar la casa por la ventana.",
            "Estar apurado/a.",
            "Buscar las cosquillas.",
            "Estar chupado.",
            "Irse por la tangente.",
            "De perdidos al río.",
            "Dormir a pierna suelta.",
            "Estar hecho un lío.",
            "Ser un enchufado.",
            "A otra cosa, mariposa.",
            "Cantar las 40.",
            "Estar como un roble.",
            "No pegarla ni con cola.",
            "Morderse la lengua.",
            "Hablar por los codos.",
            "¡Qué padre!» / «¡Qué chido!",
            "¿Qué onda?",
            "¡Qué gacho!",
            "Estar agüitado.",
            "Chavo / Chava",
            "Carnal",
            "Hazme el paro.",
            "Estar cañón.",
            "A huevo.",
            "Ponerse la del Puebla.",
            "Estar morro/a.",
            "Chambear",
            "La lana",
            "Un parote",
            "No hay bronca.",
            "Dar el avió",
            "Saber un buen.",
            "Estar fresa.",
            "Ir en friega.",
            "Hacer una pachanga.",
            "Chorizo",
            "Tirarle el rollo",
            "Estar en el chisme.",
            "Traer bronca",
            "Estar bien parote",
            "¡Órale!",
            "¡Andale!",
            "Estar al tiro",
            "Cinchado",
            "No te rajes.",
            "Estar como agua para chocolate.",
            "Sacar de onda",
            "Hacer un paro",
            "Gente bien",
            "Estar clavado/a",
            "Ponerse buzo",
            "Traer la camiseta puesta",
            "Armar un pancho",
            "Ser bien chismoso/a.",
            "Andar con todo",
            "Estar de pelos.",
            "Parce / Parcero",
            "¡Qué bacán!» / «¡Qué bacano!",
            "Dar papaya.",
            "Estar de guayabo.",
            "Parchar",
            "¡Qué chévere!",
            "Vaina",
            "Chamo / Chama",
            "Guaro",
            "Estar en la jugada.",
            "Hacer un mandado.",
            "Cogerlo con suave.",
            "Ponerse la 10.",
            "Boleto",
            "Estar corchado/a.",
            "Pelao / Pelá",
            "Estar en la olla.",
            "¡Pilas!",
            "A la orden.",
            "Dar lora.",
            "Estar cansado/a de la misma vaina.",
            "Poderoso/a",
            "Estar picado/a.",
            "Armar un parche.",
            "Tener buena onda.",
            "Hacer un cruce.",
            "Estar de un fino.",
            "No le crea tanto.",
            "¡Che!",
            "¡Qué copado!",
            "Laburar",
            "Guita",
            "Pibe / Piba",
            "Tener fiaca.",
            "Estar al horno.",
            "Ir a tomar un mate.",
            "Hacerse el desentendido.",
            "Mandar fruta.",
            "Estar re loco/a.",
            "Posta",
            "Bancar",
            "Quilombo",
            "Champán y chinchulín.",
            "Estar un toque ocupado/a.",
            "Echar un centro.",
            "Tener la posta.",
            "Estar re contento/a.",
            "Sabelo.",
            "Saltar la ficha.",
            "Estar del coco.",
            "Estar flopeando.",
            "Ser un/a hater.",
            "Dar cringe.",
            "Tener hype.",
            "Glow up",
            "Estar obsesionado/a.",
            "Modo ahorro de energía.",
            "Tener flow.",
            "Cero drama.",
            "Ser tendencia.",
            "Estar cancelado/a.",
            "Mandar mensaje directo.",
            "Hacer match.",
            "Tener buena vibra.",
            "Hacer un live.",
            "Estar viral.",
            "De una.",
            "En fin, la hipocresía.",
            "Tener una bandera roja.",
            "Estar en tu prime.",
            "Tener vibes de...",
            "Main character",
            "Hacer un meme.",
            "Estar en la zona de confort.",
            "Estar fuera de lugar.",
            "Ni al caso.",
            "Me suena bastate.",
            "Pisar el freno.",
            "Estar en sincronía.",
            "Sin palabras.",
            "Fin del comunicado.",
    };

    public SemanticMatcherEs(Context context) {
        super(context, TAG, ASSET_PATH, FALLBACK_QUESTIONS, randomActions());
    }

    /** fallback 動作全部 __RANDOM__：幾多答句就幾多個位，SemanticCenter
     *  見到呢個標記會即場隨機選動作 (見 ActionDirect.resolveRandomActionId())。 */
    private static String[] randomActions() {
        String[] a = new String[FALLBACK_QUESTIONS.length];
        for (int i = 0; i < a.length; i++) {
            a[i] = "__RANDOM__";
        }
        return a;
    }
}
