package com.open.alpha2;

import android.content.Context;

/**
 * 德文語意配對引擎 - 和 SemanticMatcherZh (中文版)／SemanticMatcherEn
 * (英文版)／SemanticMatcherEs (西班牙文版)／SemanticMatcherFr (法文版)／
 * SemanticMatcherJa (日文版) 同一套語意配對機制, 專門處理德文。
 *
 * 資料來源: assets/semantic/semantic_de.json (v2 grouped 格式, 同其他語言同一個
 * schema - 見 SemanticMatcherBase.load())。85 ACTION (id/op/slot/actionId 全同
 * 英文版；每組地道德文 5 問法＋5 答案) ＋200 日常 CHAT (de.daily.001-200，
 * 每組 5 問法＋5 答案：001-040 問候天氣、041-080 飲食、081-120 家庭家居寵物、
 * 121-160 工作學習健康、161-200 休閒旅行日常；動作全 __RANDOM__)。
 * de800（電影／名言／歌詞／潮語各 200）啱意境的已按意配入日常組答案
 * （每組最多加 3 句）；39 句粗口／暴力／陰暗／非德文剔除唔用；
 * 剩低 496 句全入下面 fallback，動作全 __RANDOM__（60 池）。
 *
 * 這個 class 只負責「文字 -> 配對結果」, 不負責執行 TTS/動作 - 跟著這個 project
 * 一貫的分層方式，執行那一步留給呼叫方 (SemanticCenter 的 handleSemanticMatch)
 * 做, 方便測試和重用。
 *
 * 只做德文 - 和其他語言版各自獨立, 沒在這個 class 裡加 language 參數
 * (因為機身 ASR 引擎本身一次只能選到一種語言, matcher 不會同時用）。
 * SemanticCenter.handleSemanticMatch() 根據對話語言／文字判斷結果, 選用哪一個。
 * 載入/比對/分類 random 的實際邏輯全部在 SemanticMatcherBase, 這裡只提供
 * 德文專屬的 TAG/assets 路徑/fallback 問法組。
 *
 * Zero-third-party-dependency: 只用 org.json (Android 內建, 經 base class), 沒額外
 * library。
 */
public class SemanticMatcherDe extends SemanticMatcherBase {
    private static final String TAG = "SemanticMatcherDe";
    private static final String ASSET_PATH = "semantic/semantic_de.json";

    /** 骨架：fallback 空池（內容後加；base.fallback() 空池回 null，唔 crash）。 */
    private static final String[] FALLBACK_QUESTIONS = {
            "Das Leben ist wie eine Schachtel Pralinen, man weiß nie, was man kriegt.",
            "Möge die Macht mit dir sein.",
            "Ich schaue dir in die Augen, Kleines.",
            "Hast du jemals mit dem Teufel im blassen Mondlicht getanzt?",
            "Wer Angst vor dem Tod hat, hat auch Angst vor dem Leben.",
            "Manchmal muss man Regeln brechen, um das Richtige zu tun.",
            "Ein Mann ohne Ideale ist kein richtiger Mann.",
            "Nichts auf der Welt ist umsonst.",
            "Das Bild auf der Leinwand verändert sich, aber die Geschichte bleibt.",
            "Die Wahrheit ist oft schmerzhafter als die Lüge.",
            "Die Vergangenheit kann man nicht ändern, aber die Zukunft schon.",
            "Manchmal muss man alles verlieren, um sich selbst zu finden.",
            "Glück ist nur real, wenn man es teilt.",
            "Wir definieren uns durch die Entscheidungen, die wir treffen.",
            "Freiheit bedeutet, keine Angst zu haben.",
            "Das Universum hat seinen eigenen Plan.",
            "Ich würde eher ein einziges Leben mit dir teilen, als alle Zeitalter dieser Welt allein zu verbringen.",
            "Du hast mich vollendet.",
            "Ich bin nur ein Mädchen, das vor einem Jungen steht und ihn bittet, es zu lieben.",
            "Ich liebe dich nicht nur für das, was du bist, sondern für das, was ich bin, wenn ich bei dir bin.",
            "Ohne dich wären die Gefühle von heute nur die leeren Hüllen der von gestern.",
            "Liebe bedeutet, niemals Um Verzeihung bitten zu müssen.",
            "Ich verspreche, dich jeden Tag ein bisschen mehr zu lieben.",
            "Du bist mein bester Freund und meine große Liebe.",
            "Manchmal ist das Herz klüger als der Verstand.",
            "Ich werde dich nie vergessen.",
            "Egal was passiert, du wirst immer in meinem Herzen sein.",
            "Du bringst mich zum Lächeln, selbst wenn mir zum Weinen ist.",
            "Mit dir fühlt sich alles so einfach an.",
            "Ich brauche nicht die ganze Welt, ich brauche nur dich.",
            "Unsere Liebe ist wie der Wind – ich kann sie nicht sehen, aber ich kann sie spüren.",
            "Ich habe dich schon gelebt, bevor ich dich traf.",
            "Wir passen zusammen wie zwei Puzzleteile.",
            "Ich würde alles noch einmal genauso machen, solange du bei mir bist.",
            "Du bist mein Licht im Dunkeln.",
            "Ich wusste vom ersten Moment an, dass du es bist.",
            "Wenn du jemanden liebst, lässt du ihn frei.",
            "Liebe ist der Schlüssel zu allem.",
            "Du bist die Antwort auf all meine Gebete.",
            "In deinen Augen sehe ich meine Zukunft.",
            "Es gibt keine Zufälle im Leben, besonders nicht in der Liebe.",
            "Ich liebe dich nicht wegen dem, wer du bist, sondern wer ich bin, wenn ich bei dir bin.",
            "Ich mache ihm ein Angebot, das er nicht ablehnen kann.",
            "Ich bin der König der Welt!",
            "Warum so ernst?",
            "Das ist kein Messer. DAS ist ein Messer!",
            "Du redest mit mir?",
            "Niemand nennt mich feige!",
            "Ich bin nicht verrückt, meine Mutter hat mich testen lassen.",
            "Ich trinke, um die anderen Leute interessanter zu machen.",
            "Ein Kluger bemerkt alles, ein Dümmlicher macht zu allem seine Bemerkungen.",
            "Ich habe nicht die Absicht, mich vernünftig zu verhalten.",
            "Manchmal überrasche ich mich selbst.",
            "Kannst du das wiederholen? Ich habe nicht zugehört.",
            "Niemand ist perfekt – außer mir.",
            "Du kannst die Wahrheit doch gar nicht vertragen!",
            "Ich habe ein ganz mieses Gefühl bei der Sache.",
            "Das ist der Tag, an dem ihr beinahe Captain Jack Sparrow gefangen hättet!",
            "Ich gebe dir eine Minute.",
            "Es gibt kein Zurück mehr.",
            "Nimm die rote Pille, und du bleibst im Wunderland.",
            "Wir sind nicht hier, um zu verhandeln.",
            "Zeig mir das Geld!",
            "Du hast nur einen Versuch.",
            "Der Feind meines Feindes ist mein Freund.",
            "Es ist Zeit, Geschichte zu schreiben.",
            "Auf mein Zeichen: Entfesselt die Hölle!",
            "Sie werden uns niemals unsere Freiheit nehmen!",
            "Ich kämpfe für diejenigen, die nicht kämpfen können.",
            "Vertraue niemandem.",
            "Der einzige Ausweg ist mitten durch.",
            "Wir müssen hier sofort verschwinden.",
            "Das ist erst der Anfang.",
            "Ich habe keine Angst vor dir.",
            "Stell keine Fragen, wenn du keine Lügen hören willst.",
            "Jeder muss sich entscheiden, auf welcher Seite er steht.",
            "Ich kenne deine Vergangenheit.",
            "Echte Freunde erkennt man in der Not.",
            "Die Vergangenheit kann wehtun. Aber man kann davon laufen oder daraus lernen.",
            "Ein Freund ist jemand, der dich mag, obwohl er dich kennt.",
            "Danke, dass du mein Freund bist.",
            "Nichts kann uns trennen.",
            "Jeder verdient eine zweite Chance.",
            "Niemand hat die Absicht, eine Mauer zu errichten!",
            "Die Wahrheit ist eine scharfe Waffe.",
            "Wir sind das Volk!",
            "Wer die Vergangenheit kontrolliert, kontrolliert die Zukunft.",
            "Freiheit ist immer Freiheit der Andersdenkenden.",
            "Systeme verändern sich, aber die Menschen bleiben dieselben.",
            "Angst ist das stärkste Werkzeug der Macht.",
            "Wenn wir jetzt nicht sprechen, wann dann?",
            "Der Mensch ist dem Menschen ein Wolf.",
            "Im Westen nichts Neues.",
            "Krieg kennt keine Gewinner, nur Überlebende.",
            "Die Geschichte wird von den Siegern geschrieben.",
            "Befehl ist Befehl?",
            "Gerechtigkeit ist nicht dasselbe wie das Gesetz.",
            "Manchmal muss man das Gesetz brechen, um der Gerechtigkeit zu dienen.",
            "Macht korrumpiert, absolute Macht korrumpiert absolut.",
            "Ein Symbol kann den Menschen Hoffnung geben.",
            "Hinter dieser Maske steckt mehr als Fleisch. Hinter dieser Maske steckt eine Idee.",
            "Man kann eine Idee nicht erschießen.",
            "Demokratie ist anstrengend, aber sie lohnt sich.",
            "Zivilisation beginnt dort, wo die Vernunft siegt.",
            "Nichts ist wie es scheint.",
            "Das Ende ist erst der Anfang.",
            "Die Zukunft gehört denen, die an die Schönheit ihrer Träume glauben.",
            "Es ist niemals zu spät, der zu sein, der man hätte werden können.",
            "Ende gut, alles gut.",
            "Zwei Dinge erfüllen das Gemüt mit immer neuer und zunehmender Bewunderung: der bestirnte Himmel über mir und das moralische Gesetz in mir.",
            "Der Mensch ist zur Freiheit verurteilt.",
            "Handele nur nach derjenigen Maxime, durch die du zugleich wollen kannst, dass sie ein allgemeines Gesetz werde.",
            "Das Leben kann nur rückwärts verstanden werden, muss aber vorwärts gelebt werden.",
            "Die Höchste Form des Glücks ist ein Leben mit einem gewissen Grad an Verrücktheit.",
            "Wer mit Ungeheuern kämpft, mag zusehen, dass er nicht dabei ein Ungeheuer wird.",
            "Neid ist die höchste Form der Anerkennung.",
            "Muße ist der Dünger des Geistes.",
            "Die Wahrheit ist dem Menschen zumutbar.",
            "Die Freiheit besteht darin, dass man alles tun kann, was einem anderen nicht schadet.",
            "Wer den Verstand verliert, hat nicht viel zu verlieren.",
            "Das Sein bestimmt das Bewusstsein.",
            "Zwei Seelen wohnen, ach! in meiner Brust.",
            "Edel sei der Mensch, hilfreich und gut!",
            "Wer nie sein Brot mit Tränen aß, der kennt euch nicht, ihr himmlischen Mächte.",
            "Die Axt im Haus erspart den Zimmermann.",
            "Sire, geben Sie Gedankenfreiheit!",
            "Der Starke ist am mächtigsten allein.",
            "Spät kommt ihr – doch ihr kommt!",
            "Es kann der Frömmste nicht in Frieden bleiben, wenn es dem bösen Nachbarn nicht gefällt.",
            "Dort wo man Bücher verbrennt, verbrennt man am Ende auch Menschen.",
            "Der Tod, das ist die kühle Nacht, das Leben ist der schwüle Tag.",
            "Aus eitler Kunst wird nie ein Werk der Liebe.",
            "Herr: es ist Zeit. Der Sommer war sehr groß.",
            "Wer jetzt kein Haus hat, baut sich keines mehr.",
            "Wenn du lange in einen Abgrund blickst, blickt der Abgrund auch in dich hinein.",
            "Ein Raum ohne Bücher ist ein Körper ohne Seele.",
            "Der Verlust der Phantasie ist der Verlust jeder Hoffnung.",
            "Es gibt nichts Gutes, außer: Man tut es.",
            "Humor ist der Knopf, der verhindert, dass uns der Kragen platzt.",
            "Stell dir vor, es ist Krieg, und keiner geht hin.",
            "Die Poesie ist das Gedächtnis der Menschheit.",
            "Fantasie ist wichtiger als Wissen, denn Wissen ist begrenzt.",
            "Gott würfelt nicht.",
            "Zwei Dinge sind unendlich, das Universum und die menschliche Dummheit, aber beim Universum bin ich mir noch nicht ganz sicher.",
            "Ich habe keine besondere Begabung, sondern bin nur leidenschaftlich neugierig.",
            "Mehr als die Vergangenheit interessiert mich die Zukunft, denn in ihr gedenke ich zu leben.",
            "Die Wahrheit stirbt nie.",
            "Und sie bewegt sich doch!",
            "Wir müssen wissen – wir werden wissen.",
            "Alles sollte so einfach wie möglich gemacht werden, aber nicht einfacher.",
            "Die Wissenschaft von heute ist die Technologie von morgen.",
            "Eine neue wissenschaftliche Wahrheit pflegt sich nicht so durchzusetzen, dass ihre Gegner überzeugt werden, sondern dass die Gegner allmählich aussterben.",
            "Man kann nicht entdeckt werden, wenn man der Herde folgt.",
            "Wenn ich weiter gesehen habe als andere, so deshalb, weil ich auf den Schultern von Riesen stand.",
            "Die Natur macht keine Sprünge.",
            "Kein Problem kann durch das selbe Bewusstsein gelöst werden, das es erzeugt hat.",
            "Das Geheimnis der Natur liegt in ihrer Einfachheit.",
            "Fortschritt ist der Weg vom Unmöglichen zum Möglichen.",
            "Technik ist die Kunst, die Natur zu überlisten.",
            "Nichts ist mächtiger als eine Idee, deren Zeit gekommen ist.",
            "Die Politik ist die Kunst des Möglichen.",
            "Demokratie ist die schlechteste aller Regierungsformen – abgesehen von allen anderen.",
            "Die Freiheit des Einzelnen endet dort, wo die Freiheit des Anderen beginnt.",
            "Mehr Demokratie wagen.",
            "Jetzt wächst zusammen, was zusammengehört.",
            "Wer in der Demokratie schläft, wacht in der Diktatur auf.",
            "Entscheidend ist, was hinten rauskommt.",
            "Gerechtigkeit ist der Grundpfeiler des Staates.",
            "Man kann nicht mit allen Menschen im Frieden leben, aber mit allen in Höflichkeit.",
            "Jeder ist seines Glückes Schmied.",
            "Einige Menschen sehen die Dinge wie sie sind und fragen: Warum? Ich träume von Dingen, die es noch nie gab und frage: Warum nicht?",
            "Pazifismus ist die Absage an jede Form von Gewalt.",
            "Freiheit bedeutet Verantwortung. Das ist der Grund, warum die meisten Menschen sich vor ihr fürchten.",
            "Der Preis der Freiheit ist ewige Wachsamkeit.",
            "Zivilisation ist die Überwindung der Rohheit.",
            "Die Zukunft hängt davon ab, was wir heute tun.",
            "Sei du selbst die Veränderung, die du dir wünschst für diese Welt.",
            "Das erste Opfer des Krieges ist die Wahrheit.",
            "Die besten Dinge im Leben sind nicht die, die man für Geld bekommt.",
            "Eifersucht ist eine Leidenschaft, die mit Eifer sucht, was Leiden schafft.",
            "Wer die Augen offen hält, dem wird das Leben reich beschenkt.",
            "Manchmal muss man tief fallen, um zu sehen, wer zu einem steht.",
            "Das Lächeln ist eine Sprache, die jeder versteht.",
            "Das Leben ist zu kurz für später.",
            "Nichts macht den Menschen mehr aus als seine Taten.",
            "Die Höflichkeit ist die eleganteste Form des Egoismus.",
            "Vergebung ist die Rache des Weisen.",
            "Erfolg ist nicht der Schlüssel zum Glück. Glück ist der Schlüssel zum Erfolg.",
            "Schönheit liegt im Auge des Betrachters.",
            "Die Musik drückt das aus, was nicht gesagt werden kann und worüber es unmöglich ist, zu schweigen.",
            "Architektur ist erstarrte Musik.",
            "Jedes Bild ist ein Gespräch zwischen dem Künstler und dem Betrachter.",
            "Das Auge macht das Bild, nicht die Kamera.",
            "Farbe ist die Taste. Das Auge ist der Hammer.",
            "Die Kunst ist der Spiegel der Seele.",
            "Musik verändert die Welt, weil sie Menschen verändert.",
            "Ohne Kunst wird es still.",
            "Kunst gibt nicht das Sichtbare wieder, sondern macht sichtbar.",
            "Die Natur erschafft Kunstwerke, ohne es zu wissen.",
            "Tanz ist die vertikale Frustration eines horizontalen Wunsches.",
            "Das Theater ist der Spiegel der Welt.",
            "Ein schönes Bild erfreut das Herz.",
            "Die Musik ist die Stimme des Universums.",
            "Kunst ist das Brot des Geistes.",
            "Stille ist das schönste Geräusch der Welt.",
            "Die Jahre lehren viel, was die Tage niemals wissen.",
            "Nichts bleibt wie es ist.",
            "Man lebet nur einmal in der Welt.",
            "Der Tod ist der Grenzstein des Lebens, aber nicht der Liebe.",
            "Das Leben ist eine Reise, kein Ziel.",
            "Am Ende zählt nicht, wie viele Jahre hat man gelebt, sondern wie viel Leben in diesen Jahren war.",
            "Die Hoffnung stirbt zuletzt.",
            "Manche Menschen hinterlassen Spuren in unserem Herzen.",
            "Wer dem Glück nachläuft, läuft ihm davon.",
            "Alles vergeht, die Erinnerung bleibt.",
            "Du hast mich gefragt, und ich hab nichts gesagt.",
            "Engel fliegen nur im Dunkeln.",
            "Ich will, dass ihr mir vertraut.",
            "Manchmal muss man untergehen, um zu verstehen.",
            "Amerika ist wunderbar.",
            "Wir wollen die Welt brennen sehen.",
            "An Tagen wie diesen wünscht man sich Unendlichkeit.",
            "Wir sind die Nacht, wir sind der Sturm.",
            "Willkommen in der Dunkelheit.",
            "Du bist der Schmerz, der mich am Leben hält.",
            "Durch den Monsun, hinter die Welt.",
            "Rette mich, ich verfalle in der Nacht.",
            "Aus Feuer und Stahl wurden wir geboren.",
            "Keine Macht für niemand!",
            "Wir sterben niemals aus.",
            "Wir sind groß, unsere Träume sind riesengroß.",
            "Lieder, die Geschichte schrieben.",
            "Nur ein Lied entfernt von dir.",
            "An guten Tagen gibt es kein Zögern.",
            "Wenn du mich fragst, war es die beste Zeit.",
            "Ey, da müsste Musik sein, überall wo du bist.",
            "An Wunder glauben wir schon lange nicht mehr.",
            "Wer wenn nicht wir, wann wenn nicht jetzt?",
            "Auf das, was uns verbindet!",
            "Gibt mir ein kleines bisschen Sicherheit.",
            "Das Beste was mir je passiert ist, bist du.",
            "Ich trag dich durch die schweren Zeiten.",
            "Cello, du spieltest Cello.",
            "Hinter dem Horizont geht’s weiter.",
            "Bleib genauso wie du bist, denn so bist du perfekt.",
            "Ich will nur, dass du weißt, wie viel du mir bedeutest.",
            "Liebe meines Lebens, wo bist du?",
            "Halt mich fest, bis der Morgen kommt.",
            "Männer haben’s schwer, nehmen’s leicht.",
            "Männer weinen heimlich.",
            "Sie fehlt in jedem Raum.",
            "Ich hab Fotos im Kopf, die kann niemand löschen.",
            "Erfolg ist kein Glück, sondern das Ergebnis von Blut, Schweiß und Tränen.",
            "Alles wird gut, vielleicht nicht heute, aber irgendwann.",
            "Ich renne durch die Stadt in der Nacht.",
            "Hi Kids, ich bin’s, der Panda.",
            "Mach dir keine Sorgen, alles ist easy.",
            "Einmal um die Welt, Taschen voller Geld.",
            "Bye Bye, meine liebe Sorge.",
            "Sie wollen sein wie wir.",
            "Kein Problem, ich fahr auf meinem Roller davon.",
            "Du knallst in mein Leben wie ein Komet.",
            "Lass uns ein Zeichen setzen, das für immer bleibt.",
            "Ich war noch niemals in New York.",
            "Sie wissen genau, wer wir sind.",
            "Nachts auf den Straßen der Stadt.",
            "500 PS unter der Haube.",
            "Das ist der beste Tag meines Lebens.",
            "Zusammen ist man weniger allein.",
            "Alle meine Freunde sind hier.",
            "Guten Morgen, Berlin, du kannst so hässlich sein.",
            "Ich verbrenne mein Studio, schnappe mir mein Geld.",
            "Freude, schöner Götterfunken, Tochter aus Elysium!",
            "Alle Menschen werden Brüder, wo dein sanfter Flügel weilt.",
            "Die Hölle Rache kocht in meinem Herzen!",
            "Der Hölle Rache kocht in meinem Herzen, Tod und Verzweiflung flammet um mich her!",
            "Dies Bildnis ist bezaubernd schön!",
            "In diesen heil'gen Hallen kennt man die Rache nicht.",
            "Reich mir die Hand, mein Leben!",
            "Röslein wehrte sich und stach, half ihr doch kein Weh und Ach.",
            "Mein Vater, mein Vater, und siehest du nicht, Erlenkönig mit Kron’ und Schweif?",
            "Ich liebe dich, so wie du mich, am Abend und am Morgen.",
            "O du mein holder Abendstern!",
            "In fernem Land, unnahbar euren Schritten...",
            "Treulich geführt ziehet dahin!",
            "Morgenlich leuchtend im rosigen Schein.",
            "Mild und leise wie er lächelt.",
            "Träume, die im Dunkeln blühen.",
            "Denn alles Fleisch, es ist wie Gras.",
            "Die Nachtigall singt im Verborgenen.",
            "Du bist wie eine Blume, so hold und schön und rein.",
            "Ich bin der Festplatten-Speicher.",
            "Sie trinkt im Nachtclub ihren Champagner.",
            "Da da da, ich lieb dich nicht, du liebst mich nicht.",
            "Major Tom völlig losgelöst von der Erde.",
            "Völlig losgelöst schwebt das Raumschiff völlig schwerelos.",
            "Hast du etwas Zeit für mich? Dann singe ich ein Lied für dich.",
            "Irgendwie, irgendwo, irgendwann.",
            "Liebe wird aus Mut gemacht.",
            "Nur geträumt von dir und mir.",
            "Sternenhimmel über Berlin.",
            "Der Kommissar geht um! Oh oh!",
            "Dreh dich nicht um, der Kommissar geht um.",
            "Er war ein Punker und er lebte in der großen Stadt.",
            "Wer hat an der Uhr gedreht? Ist es wirklich schon so spät?",
            "Oft gefragt, nie geantwortet.",
            "Du bist zu Hause, wenn ich bei dir bin.",
            "Pocahontas, du kannst jetzt nicht gehen.",
            "Ich will nicht nach Berlin.",
            "Unsere Fans sind die besten der Welt.",
            "Ich will nicht gehorsam, gezähmt und gezogen sein!",
            "Die Schatten werden länger.",
            "Kitsch, alles nur Kitsch!",
            "Totale Finsternis, ein Meer von Gefühl.",
            "Draußen ist Freiheit, draußen ist Licht.",
            "Unstillbare Gier nach Leben.",
            "Mehr will ich nicht von dir.",
            "Über den Wolken muss die Freiheit wohl grenzenlos sein.",
            "Alle Ängste, alle Sorgen, sagt man, blieben darunter verborgen.",
            "Marmorglas und Eisen bricht, aber unsere Liebe nicht.",
            "Liebeskummer lohnt sich nicht, my Darling.",
            "Fiesta Mexicana, wir feiern die ganze Nacht.",
            "Atemlos durch die Nacht.",
            "Spür was Liebe mit uns macht.",
            "Herzbeben, lass uns zusammen fliegen.",
            "Du hast mich tausendmal belogen.",
            "Ich will der Allerbeste sein, wie keiner vor mir war.",
            "Ganz allein fange ich sie mir, ich kenne die Gefahr.",
            "Pokémon! Komm schnapp dir alle!",
            "Cha-La Head-Cha-La, keine Sorge, es wird schon geh’n!",
            "Flieg durch die Zeit, kämpfe für das Licht!",
            "Sag das Zauberwort und du hast die Macht!",
            "Detektiv Conan, der Fall ist noch nicht gelöst!",
            "Digimon, digital Monsters, die Helden dieser Welt!",
            "Pippi Langstrumpf, hei-ho-hopsasa!",
            "Ich mach’ mir die Welt, wie sie mir gefällt!",
            "Zwei mal drei macht vier, widdewiddewitt und zwei macht neun!",
            "Heidi, Heidi, deine Welt sind die Berge!",
            "Dunkle Tannen, grüne Wiesen im Sonnenschein.",
            "Und diese Biene, die ich meine, nennt sich Maja.",
            "Auf der Mauer, auf der Lauer sitzt eine kleine Wanze.",
            "Komm ein bisschen mit nach Italien!",
            "Lass die Sonne in dein Herz!",
            "Ein bisschen Frieden, ein bisschen Sonne für diese Erde.",
            "Wyld / Wild",
            "Lost",
            "Sus",
            "Side Eye",
            "Rizz",
            "Main Character Energy",
            "Flexen",
            "Slay",
            "No Cap",
            "POV",
            "Same Energy",
            "Glow Up",
            "NPC",
            "Smash",
            "Pass",
            "Ghosten",
            "Simp",
            "GigaChad",
            "Lowkey",
            "Highkey",
            "Cringe-Momente",
            "Situationship",
            "Red Flag",
            "Green Flag",
            "Beziehungskiller",
            "Friendzone",
            "Breadcrumbing",
            "Gaslighting",
            "Love Bombing",
            "Benching",
            "Cuffing Season",
            "Soft Launch",
            "Hard Launch",
            "Ich hab Vibe mit ihm/ihr.",
            "Er/Sie ist ein 10/10.",
            "Bae",
            "Feste Beziehung?",
            "Single wie nie.",
            "Fast-Forwarding",
            "Toxic",
            "Ihre Chemistry stimmt.",
            "Hab mich verguckt.",
            "Sneaky Link",
            "Safe Bet",
            "Wir sind gechillt.",
            "Kein Stress, lass einfach gucken.",
            "Digga / Digger",
            "Abooo!",
            "Wallah!",
            "Läuft bei dir!",
            "Das ist doch Schmutz!",
            "Voll cringe, Brudi.",
            "Bodenlos!",
            "Same here.",
            "Hör mir auf damit!",
            "Das ist der Hammer!",
            "Voll geil!",
            "Mach kein Auge!",
            "Ich bin bedient!",
            "Mach kein Drama!",
            "Spinnst du?",
            "Chill mal dein Leben!",
            "Geht klar!",
            "Passt schon.",
            "Quatsch nicht!",
            "Ich habe fertig.",
            "Alles Gutie!",
            "Alles Paletti?",
            "Fit wie ein Turnschuh.",
            "Ich bin raus.",
            "Ich bin dabei!",
            "Komm schon!",
            "Das läuft von allein.",
            "Mach dein Ding!",
            "Overkill",
            "Slow down!",
            "Keine Panik!",
            "Gute Vibes!",
            "Off-grid sein",
            "Multitasking-Profi",
            "Abreagieren",
            "Vorglühen / Vortrinken",
            "Abriss!",
            "Feiern gehen",
            "Kater am nächsten Tag",
            "Exen!",
            "Prost, ihr Säcke!",
            "Einen heben",
            "Dicht sein / Zu sein",
            "Club-Hopping",
            "Türsteher-Problem",
            "Der Bass muss scheppern!",
            "Durchmachen",
            "Zapfenstreich!",
            "Einen im Tee haben",
            "Partylöwe",
            "Katerstimmung",
            "Trinkspiel",
            "Wir machen durch bis morgen früh!",
            "Drauf sein",
            "Work-Life-Balance",
            "Bammel haben",
            "Durchgefallen!",
            "Bulimielernen",
            "Prokrastinieren",
            "Kein Bock auf Arbeit.",
            "Homeoffice-Modus",
            "Overdressed",
            "Underdressed",
            "Brainstormen",
            "Das machen wir nach dem Feierabend.",
            "Dauerstress",
            "Besserwisser / Klugscheißer",
            "Hast du Tomaten auf den Augen?",
            "Du hast wohl ’ne Meise!",
            "Das ist mir komplett wumpe / rille!",
            "Red nicht um den heißen Brei herum!",
            "Du gehst mir auf den Keks / Senkel!",
            "Ich glaub, ich spinne!",
            "Hör auf zu heulen!",
            "Alles Fassade!",
            "Du bist wohl im falschen Film!",
            "Laber nicht!",
            "Alter Schwede!",
            "Jetzt schlägt’s aber 13!",
            "Du nimmst mich wohl auf den Arm!",
            "Das kannst du deinem Friseur erzählen!",
            "Das ist uncool.",
            "Du hast den Schuss nicht gehört!",
            "Nicht dein Ernst, oder?",
            "Schau mal auf dein Leben!",
            "Kein Kommentar.",
            "Träum weiter!",
            "Was geht, Abfahr'n?",
            "Alles Celo?",
            "Bruder, muss los!",
            "Chill dein Base!",
            "Sauf nicht so viel!",
            "Mach die Robbe!",
            "Abo, wie sieht der denn aus?",
            "Gib ihm / Gib ihr!",
            "Hype ist real!",
            "Fitna machen",
            "Para machen",
            "Chillen mit den Jungs",
            "Mädelsabend",
            "Safe Digga!",
            "Kiez-Tour",
            "Lass stecken!",
            "Bis dann, Antenne!",
            "Tschüssikowski!",
            "Wir riechen uns!",
    };

    public SemanticMatcherDe(Context context) {
        super(context, TAG, ASSET_PATH, FALLBACK_QUESTIONS, randomActions());
    }

    /** fallback 動作全部 __RANDOM__：幾多答句就幾多個位，SemanticCenter
     *  見到呢個標記會即場隨機選動作 (見 ActionDirect.resolveRandomActionId())。 */
    private static String[] randomActions() {
        String[] a = new String[FALLBACK_QUESTIONS.length];
        for (int i = 0; i < a.length; i++) {
            a[i] = "__RANDOM__";
        }
        return a;
    }
}
