package com.open.alpha2;

import android.content.Context;

/**
 * 法文語意配對引擎 - 和 SemanticMatcherZh (中文版)／SemanticMatcherEn
 * (英文版)／SemanticMatcherEs (西班牙文版) 同一套語意配對機制, 專門處理法文。
 *
 * 資料來源: assets/semantic/semantic_fr.json (v2 grouped 格式, 同其他語言同一個
 * schema - 見 SemanticMatcherBase.load())。85 ACTION (同西版同 op/actionId,
 * 補到每組 5 問法＋5 通用法文答案) ＋ 200 CHAT 日常組 (fr.daily.001-200,
 * 每組地道法文 5 問法＋5 個答案：001-040 問候天氣、041-080 飲食、
 * 081-120 家庭家居寵物、121-160 工作學習健康、161-200 休閒旅行日常；
 * 問法 tu 式日常口語寫成，唔係翻譯；fr800 (電影／歌詞／名言／潮語各 200)
 * 啱意境的已按意配入答案，剩句全入下面 fallback；200 日常組動作全 __RANDOM__
 * (fallback 60 池，播嗰刻先 resolve，同 fallback 做法一致)。
 *
 * 這個 class 只負責「文字 -> 配對結果」, 不負責執行 TTS/動作 - 跟著這個 project
 * 一貫的分層方式，執行那一步留給呼叫方 (SemanticCenter 的 handleSemanticMatch)
 * 做, 方便測試和重用。
 *
 * 只做法文 - 和其他語言版各自獨立, 沒在這個 class 裡加 language 參數
 * (因為機身 ASR 引擎本身一次只能選到一種語言, matcher 不會同時用）。
 * SemanticCenter.handleSemanticMatch() 根據對話語言／文字判斷結果, 選用哪一個。
 * 載入/比對/分類 random 的實際邏輯全部在 SemanticMatcherBase, 這裡只提供
 * 法文專屬的 TAG/assets 路徑/fallback 問法組。
 *
 * Zero-third-party-dependency: 只用 org.json (Android 內建, 經 base class), 沒額外
 * library。
 */
public class SemanticMatcherFr extends SemanticMatcherBase {
    private static final String TAG = "SemanticMatcherFr";
    private static final String ASSET_PATH = "semantic/semantic_fr.json";

    /** fallback 答句池 - fr800.txt 用剩的未配對句全數搬過嚟 (generated, 唔好手改；
     *  要加減句請改 french_raw_lines.json + semantic_fr.json 配對結果再 rerun；
     *  粗口/性/自殺及死亡陰暗句已剔除，唔入池)。
     *  聽唔明就隨機噏一句，動作全部 __RANDOM__ (SemanticCenter 見到會即場由隨機
     *  filler 池 60 個裡面選一個)，次次唔同 - 同中日西版的 fallback 做法一致。 */
    private static final String[] FALLBACK_QUESTIONS = {
            "Sans toi, les émotions d'aujourd'hui ne seraient que la peau morte des émotions d'autrefois.",
            "Vous ne serez jamais un légume, même les légumes ont du cœur.",
            "C'est pas parce qu'il est handicapé qu'il doit pas être poli !",
            "L'important c'est pas la chute, c'est l'atterrissage.",
            "Jusqu'ici tout va bien...",
            "Ne dis jamais jamais, il y a toujours quelque chose à tenter.",
            "J'ai de l'empathie, mais je n'ai pas de compassion.",
            "Qu'est-ce que je peux faire ? Je sais pas quoi faire.",
            "Je t'aime parce que tu es toi.",
            "Aimer, c'est agir.",
            "Tant qu'il y aura un homme dans la misère, le monde ne sera pas libre.",
            "On n'est pas des pigeons.",
            "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.",
            "Je vous aime. Je ne sais pas comment, ni quand, ni d'où.",
            "Nous voulons tout, et nous le voulons maintenant.",
            "Tu es la seule personne qui me fasse me sentir vivante.",
            "Si tu ne m'aimes pas, je t'aime. Et si je t'aime, prends garde à toi !",
            "Rien n'est jamais vraiment perdu tant qu'on s'en souvient.",
            "Je me souviens de chaque seconde passée avec toi.",
            "Tu ne peux pas changer le passé, mais tu peux gâcher le présent.",
            "Dans la vie, il n'y a pas de regrets, seulement des leçons.",
            "Le véritable amour n'a pas de fin.",
            "Je t'aimerai jusqu'à la fin des temps.",
            "La beauté est dans les yeux de celui qui regarde.",
            "Je suis le maître de mon destin, je suis le capitaine de mon âme.",
            "Le cœur a ses raisons que la raison ne connaît point.",
            "On ne choisit pas de qui on tombe amoureux.",
            "On a tous une chance, il faut juste savoir la saisir.",
            "Pour moi, le luxe, c’est de vivre comme on veut.",
            "Un homme sans passé n’a pas d’avenir.",
            "Il n’y a pas de problème, il n’y a que des solutions.",
            "Ce n’est pas le monde qui doit changer, c’est nous.",
            "La peur est le plus grand ennemi de l’homme.",
            "Chaque choix qu’on fait détermine qui on devient.",
            "Si on ne tente rien, on n’a rien.",
            "On passe sa vie à attendre le bon moment, mais le bon moment, c’est maintenant.",
            "Le destin est une question de choix, pas de chance.",
            "Il faut toujours croire en ses rêves, même les plus fous.",
            "La liberté, c’est de ne rien avoir à perdre.",
            "La vie n’est pas parfaite, mais elle contient des moments parfaits.",
            "La vérité est souvent bien plus étrange que la fiction.",
            "Attention, ça va couper !",
            "Mais vous savez, moi je ne crois pas qu’il y ait de bonne ou de mauvaise situation.",
            "C’est la piquette, Jack ! Tu sais pas ce que tu perds !",
            "C’est étourdissant, c’est fantastique, c’est renversant !",
            "Il est fou, ce Romain !",
            "C’est pas mon problème.",
            "Dis-moi que tu m’aimes, même si c’est un mensonge.",
            "Embrasse-moi, embrasse-moi vite !",
            "Atchoum ! — À vos souhaits.",
            "C’est magnifique, mais ce n’est pas la guerre.",
            "Le sourire est la plus belle chose qu’on puisse porter.",
            "Je ne regrette rien.",
            "La vie en rose, c’est quand je te vois.",
            "Rien n’est impossible, seules les limites existent dans notre esprit.",
            "L’amour est la seule chose qui transcende le temps et l’espace.",
            "Il n’y a pas de monstres, seulement des gens incompris.",
            "Je ne suis pas fou, ma réalité est juste différente de la tienne.",
            "Un grand pouvoir implique de grandes responsabilités.",
            "Hasta la vista, baby.",
            "On ne naît pas femme, on le devient.",
            "Après tout, demain est un autre jour.",
            "La seule façon d'échapper à la tentation, c'est d'y céder.",
            "Mon précieux...",
            "Pourquoi cet air si sérieux ?",
            "Éléments, mon cher Watson.",
            "Carpe diem. Profitez du jour présent.",
            "Ô Capitaine ! Mon Capitaine !",
            "Ce n'est pas notre aptitude qui détermine notre destin, c'est nos choix.",
            "Pour toujours et à jamais.",
            "Garde tes amis près de toi, et tes ennemis encore plus près.",
            "La première règle du Fight Club est : il est interdit de parler du Fight Club.",
            "Je vais lui faire une proposition qu'il ne refusera pas.",
            "T'as un regard qui me donne envie de faire des bêtises.",
            "On s'est aimés, on s'est quittés, on s'est retrouvés.",
            "Si tu sautes, je saute, n'est-ce pas ?",
            "Aime-moi si tu l'oses.",
            "Cap ou pas cap ?",
            "J'ai passé toute ma vie à avoir peur. Aujourd'hui, je n'ai plus peur.",
            "Les rêves sont les réponses d'aujourd'hui aux questions de demain.",
            "Tu es une étincelle dans la nuit.",
            "On ne guérit jamais vraiment d'un premier amour.",
            "Le temps efface tout, sauf les mauvais souvenirs.",
            "Le temps détruit tout.",
            "La vérité vous rendra libres.",
            "Chaque seconde est une seconde chance.",
            "Il n'y a pas d'amour, il n'y a que des preuves d'amour.",
            "La folie, c'est de faire toujours la même chose et d'attendre un résultat différent.",
            "Je t'aime plus que hier, moins que demain.",
            "Dans un monde plein de haine, il faut oser aimer.",
            "On n'oublie jamais, on apprend juste à vivre avec.",
            "Sois toi-même, tous les autres sont déjà pris.",
            "La vie est trop courte pour la passer à regretter.",
            "C'est dans tes yeux que je vois mon avenir.",
            "Je n'ai pas peur de la mort, j'ai peur de te perdre.",
            "Mon cœur ne bat que pour toi.",
            "Sans toi, la vie n'est qu'un décor vide.",
            "Il n'y a pas de distance trop grande pour deux cœurs qui s'aiment.",
            "C'est la chose la plus folle que j'aie jamais faite, mais je ne la regrette pas.",
            "Chaque regard de toi est une promesse.",
            "On ne contrôle pas les sentiments.",
            "Rien ne peut séparer deux âmes sœurs.",
            "Je préfère mourir demain que vivre un siècle sans te connaître.",
            "La vie sans passion n'a aucun sens.",
            "Quand on aime quelqu'un, on ne l'abandonne jamais.",
            "L'amour nous rend plus forts, mais aussi plus vulnérables.",
            "Je te chercherai dans chaque vie.",
            "Tu es mon plus beau secret.",
            "Ne m'oublie pas, s'il te plaît.",
            "Il n'y a rien de plus fort que la volonté humaine.",
            "La confiance se gagne en gouttes et se perd en litres.",
            "N'aie pas peur de briller.",
            "Le passé peut faire mal, mais on peut soit le fuir, soit en apprendre.",
            "N'oublie jamais qui tu es.",
            "Le monde est à nous.",
            "Si tu veux changer le monde, commence par toi-même.",
            "L'amour ne meurt jamais.",
            "Tu es la seule raison pour laquelle je respire.",
            "La liberté a un prix, et je suis prêt à le payer.",
            "Tout arrive pour une raison.",
            "Tu es mon histoire sans fin.",
            "Rien ne nous séparera jamais.",
            "Quand il me prend dans ses bras, il me parle tout bas, je vois la vie en rose.",
            "Non, je ne regrette rien, ni le bien qu'on m'a fait, ni le mal.",
            "L'amour est un oiseau rebelle que nul ne peut apprivoiser.",
            "Ne me quitte pas, il faut oublier, tout peut s'oublier.",
            "La bohème, la bohème, ça voulait dire on est heureux.",
            "Et si tu n'existais pas, dis-moi pourquoi j'existerais ?",
            "Savoir aimer, sans rien attendre en retour.",
            "Ma liberté de penser.",
            "Je l'aime à mourir.",
            "Je viens du sud et par tous mes chemins, j'y reviens.",
            "Pour que tu m'aimes encore.",
            "J'irai chercher ton cœur si tu l'emportes ailleurs.",
            "On ne change pas, on met juste des costumes.",
            "Belle, c'est un mot qu'on dirait inventé pour elle.",
            "Il est venu le temps des cathédrales.",
            "Le monde est stone.",
            "J'ai cherché un sens à mon existence.",
            "C'est la chenille qui redémarre !",
            "Aimer, c'est ce qu'il y a de plus beau.",
            "Les rois du monde vivent au sommet.",
            "Si j'avais le temps, je rattraperais le temps perdu.",
            "Alexandrie, Alexandra, ce soir je danse dans tes bras.",
            "Savoir dire non quand tout le monde dit oui.",
            "Je ne suis pas un héros.",
            "Tous les cris les SOS partent dans l'air.",
            "Mistral gagnant, le temps est un voleur.",
            "La corrida, faut-il en rire ou en pleurer ?",
            "Sensualité, je veux donner du sens à mes pensées.",
            "Désenchantée, tout est chaos à côté.",
            "Les mots bleus, ceux qu'on dit avec les yeux.",
            "Aline, pour qu'elle revienne, j'ai crié, j'ai crié.",
            "Je te donne mes notes, je te donne mes armes.",
            "Envole-moi, loin de cette fatalité.",
            "Pas toi, mais pas n'importe qui.",
            "J'ai demandé à la lune si tu voulais encore de moi.",
            "L'aventurier, contre tout guerrier.",
            "Tous les mêmes, et y en a marre.",
            "Tout oublier, il suffit d'y croire.",
            "Balance ton quoi, un jour ça changera.",
            "Oui ou non, faut se décider.",
            "Djadja, y a pas moyen Djadja.",
            "Pookie, fermer la porte, il y a les pookie.",
            "Tourner dans le vide, il me fait tourner.",
            "Ego, ego, entre mon ombre et la lumière.",
            "Secret, je garde mon secret pour toi.",
            "Andalouse, tu es ma reine.",
            "Bella, quand elle danse elle me rend fou.",
            "Changer, j'ai essayé de tout changer.",
            "J'me tire, me demande pas pourquoi.",
            "Est-ce que tu m'aimes ? Je ne sais pas.",
            "Andalouse, viens avec moi.",
            "Yeux disent ce que le cœur cache.",
            "Trop beau, pour être vrai.",
            "Dommage, il aurait dû le faire.",
            "Demain c'est loin, mais demain c'est déjà là.",
            "Comme d'hab, on fait semblant.",
            "Basique, simple, vous n'avez pas les bases.",
            "La quête, j'ai traversé le monde.",
            "San, efface tout et recommence.",
            "Au dd, on est venus pour tout prendre.",
            "A l'ammoniaque, mon cœur s'éteint.",
            "Réseaux, elle m'a capté sur le réseau.",
            "Médusa, regarde-moi dans les yeux.",
            "Bande organisée, personne peut nous arrêter.",
            "Besoin de rien, envie de toi.",
            "Femme libérée, tu sais ce que tu veux.",
            "Tombé pour elle, perdu dans ses yeux.",
            "L'envie d'avoir envie.",
            "Que je t'aime, que je t'aime !",
            "Marie, si tu savais tout le mal que l'on me fait.",
            "Diego, libre dans sa tête.",
            "Ella, elle l'a, ce je-ne-sais-quoi.",
            "Résiste, prouve que tu existes.",
            "Il jouait du piano debout.",
            "Quelque chose de Tennessee.",
            "Un autre monde, où la vie serait plus douce.",
            "Cendrillon pour ses vingt ans.",
            "Ça c'est vraiment toi !",
            "La bombe humaine, c'est toi, c'est moi.",
            "New York avec toi, n'importe où.",
            "Si seulement je pouvais lui dire.",
            "Un jour au mauvais endroit.",
            "Around the world, le monde tourne.",
            "One more time, on va danser toute la nuit.",
            "Lady, hear me tonight.",
            "Les feuilles mortes se ramassent à la pelle.",
            "Le lion est mort ce soir, dans la jungle.",
            "Foule sentimentale, on nous fait croire des choses.",
            "Sous les jupes des filles, un vent de liberté.",
            "La ballade de Jim, sur la route.",
            "Quand j'serai K.O., tu me ramasseras.",
            "Je t'aime moi non plus, dit la chanson.",
            "La javanaise, nous nous aimions le temps d'une chanson.",
            "Bonnie and Clyde, nous traversons la vie ensemble.",
            "Initials B.B., gravées dans mon cœur.",
            "Chanson sur ma drôle de vie.",
            "Besoin de personne, je trace ma route.",
            "Quelqu'un m'a dit que tu m'aimais encore.",
            "Raphaël, il a l'air d'un ange.",
            "Le temps de l'amour, le temps des copains.",
            "Tous les garçons et les filles de mon âge.",
            "La maladie d'amour, ça court dans les cœurs.",
            "Être une femme, libérée et forte.",
            "Le rire du sergent, une vieille histoire.",
            "Un homme heureux, c'est tout ce que je veux.",
            "Fais-moi une place, au fond de ton cœur.",
            "Ma préférence, c'est toi.",
            "Mélance, petite sœur de mon âme.",
            "Femmes, je vous aime.",
            "Cœur de rocker, sous la veste en cuir.",
            "Andy, dis-moi que tu m'aimes.",
            "Marcia Baïla, elle danse la vie.",
            "Les histoires d'A., finissent mal en général.",
            "C'est comme ça, on n'y peut rien.",
            "Tombé pour la France, souvenirs de guerre.",
            "Epaule tattoo, marquée pour la vie.",
            "Bleu comme toi, la couleur de mes rêves.",
            "Sur mon épaule, tu peux poser ta tête.",
            "L'Amérique pleure, sur ses erreurs.",
            "Marine, j'ai écrit cette chanson pour toi.",
            "La boulette, génération désenchantée.",
            "Je jeune et con, comme tant d'autres.",
            "Sauver l'amour, avant qu'il ne soit trop tard.",
            "L'aziza, ta couleur est une richesse.",
            "La vie ne m'apprend rien.",
            "Je pense, donc je suis.",
            "L'homme est né libre, et partout il est dans les fers.",
            "L'enfer, c'est les autres.",
            "Le seul moyen de se délivrer d'une tentation, c'est y céder.",
            "La vie est un sommeil, l'amour en est le rêve.",
            "Il n'y a qu'un bonheur dans la vie, c'est d'aimer et d'être aimé.",
            "Le secret de la liberté, c'est l'éducation.",
            "L'ignorance est la mère de tous les maux.",
            "Rien ne se perd, rien ne se crée, tout se transforme.",
            "Le savoir est la seule matière qui s'accroît quand on la partage.",
            "La simplicité est la sophistication suprême.",
            "Vivre, c'est obstinément continuer d'espérer.",
            "Il faut imaginer Sisyphe heureux.",
            "L'absurde naît de cette confrontation entre l'appel humain et le silence déraisonnable du monde.",
            "L'existence précède l'essence.",
            "Nous sommes nos choix.",
            "L'homme est condamné à être libre.",
            "La parole a été donnée à l'homme pour déguiser sa pensée.",
            "L'homme qui ne lit pas n'a aucun avantage sur celui qui ne sait pas lire.",
            "Savoir, c'est pouvoir.",
            "Les vrais miracles font peu de bruit.",
            "Rien de grand ne s'est accompli dans le monde sans passion.",
            "Chaque homme est le constructeur de son propre temple.",
            "Il est grand temps de rallumer les étoiles.",
            "Ce n'est pas parce que les choses sont difficiles que nous n'osons pas, c'est parce que nous n'osons pas qu'elles sont difficiles.",
            "La vie est courte, mais l'art est long.",
            "L'expérience est le nom que chacun donne à ses erreurs.",
            "Le plus grand risque est de ne prendre aucun risque.",
            "La beauté est dans l'œil de celui qui regarde.",
            "Il n'y a pas de réussite facile ni de échecs définitifs.",
            "On n'apprend rien quand on parle.",
            "La liberté commence où l'ignorance finit.",
            "Ce qui ne me tue pas me rend plus fort.",
            "Le courage, c'est de chercher la vérité et de la dire.",
            "L'esprit est comme un parachute, il ne fonctionne que s'il est ouvert.",
            "Tous les grands personages ont d'abord été des enfants, mais peu d'entre eux s'en souviennent.",
            "C'est le temps que tu as perdu pour ta rose qui rend ta rose si importante.",
            "Tu es responsable pour toujours de ce que tu as apprivoisé.",
            "Fais de ta vie un rêve, et d'un rêve, une réalité.",
            "Aimer, c'est savoir dire je t'aime sans parler.",
            "Un poète est un monde enfermé dans un homme.",
            "Changer la vie.",
            "Je est un autre.",
            "Il faut être absolument moderne.",
            "La vie est ailleurs.",
            "Tu m'as donné ta boue et j'en ai fait de l'or.",
            "Le beau est toujours bizarre.",
            "Sois sage, ô ma Douleur, et tiens-toi plus tranquille.",
            "La mémoire du cœur efface les mauvais souvenirs et embellit les bons.",
            "Il n'y a pas de chef-d'œuvre sans passion.",
            "La parole est à moitié à celui qui parle, moitié à celui qui l'écoute.",
            "Le style, c'est l'homme même.",
            "Les mots sont des pistolets chargés.",
            "Écrire, c'est une façon de parler sans être interrompu.",
            "Créer, c'est vivre deux fois.",
            "Il n'y a rien de plus artistique que d'aimer les gens.",
            "Si vous entendez une voix en vous qui dit \"tu ne peux pas peindre\", alors peignez et cette voix se taira.",
            "J'ai mis toute ma vie à savoir dessiner comme un enfant.",
            "La couleur est le clavier, les yeux sont les marteaux, l'âme est le piano.",
            "L'amour est un tyran qui n'épargne personne.",
            "C'est cela l'amour, tout donner, tout sacrifier sans espoir de retour.",
            "Aimer, ce n'est pas se regarder l'un l'autre, c'est regarder ensemble dans la même direction.",
            "La poésie est cette musique que tout homme porte en soi.",
            "La vie est une comédie pour ceux qui pensent, une tragédie pour ceux qui sentent.",
            "Rien n'est plus dangereux qu'une idée quand on n'en a qu'une.",
            "Le doute est le commencement de la sagesse.",
            "Rien ne résiste à l'insistance.",
            "L'imagination gouverne le monde.",
            "On ne fait rien de grand sans grands hommes, et ils le sont pour l'avoir voulu.",
            "Impossible n'est pas français.",
            "Du haut de ces pyramides, quarante siècles vous contemplent.",
            "Quand la Chine s'éveillera, le monde tremblera.",
            "Paris outrage ! Paris brisé ! Paris martyrisé ! Mais Paris libéré !",
            "La France a perdu une bataille ! Mais la France n'a pas perdu la guerre !",
            "L'État, c'est moi.",
            "Après moi, le déluge.",
            "Liberté, Égalité, Fraternité.",
            "Je ne suis pas d'accord avec ce que vous dites, mais je me battrai jusqu'à la mort pour que vous puissiez le dire.",
            "Pour être grand, il faut avoir été petit.",
            "Veni, vidi, vici.",
            "Un peuple qui oublie son passé se condamne à le revivre.",
            "Soyez le changement que vous voulez voir dans le monde.",
            "La politique est l'art du possible.",
            "Un droit n'est jamais donné, il est conquis.",
            "La justice sans la force est impuissante ; la force sans la justice est tyrannique.",
            "Quand les hommes ne peuvent changer les choses, ils changent les mots.",
            "Ne demandez pas ce que votre pays peut faire pour vous, demandez ce que vous pouvez faire pour votre pays.",
            "La démocratie est le pire des systèmes, à l'exception de tous les autres.",
            "Rien ne se construit dans la haine.",
            "Le destin n'est pas une question de chance, c'est une question de choix.",
            "La guerre est une chose trop grave pour la confier à des militaires.",
            "Pour triompher, le mal n'a besoin que de l'inaction des hommes de bien.",
            "La paix n'est pas l'absence de guerre, c'est une vertu.",
            "Il faut toujours viser la lune, car même en cas d'échec, on atterrit dans les étoiles.",
            "On ne résout pas un problème avec le mode de pensée qui l'a créé.",
            "Le futur appartient à ceux qui croient à la beauté de leurs rêves.",
            "Le patriotisme, c'est l'amour des siens ; le nationalisme, c'est la haine des autres.",
            "L'histoire est écrite par les vainqueurs.",
            "La liberté des uns s'arrête là où commence celle des autres.",
            "Tout passe, tout casse, tout lasse.",
            "Aux grands hommes, la patrie reconnaissante.",
            "Aide-toi, le ciel t'aidera.",
            "Il n'y a pas de fumée sans feu.",
            "Chacun voit midi à sa porte.",
            "Goutte à goutte, eau creuse la pierre.",
            "C'est en forgeant qu'on devient forgeron.",
            "La mode passe, le style reste.",
            "La simplicité est la clé de toute élégance véritable.",
            "Une femme sans parfum est une femme sans avenir.",
            "Pour être irremplaçable, il faut toujours être différent.",
            "Les vêtements ne changent pas le monde, les femmes qui les portent le font.",
            "L'élégance n'est pas de se faire remarquer, c'est de se faire remarquer sans le vouloir.",
            "Les plus belles choses de la vie ne sont pas des choses.",
            "Dans la vie, rien n'est à craindre, tout est à comprendre.",
            "Soyez moins curieux des personnes et plus curieux des idées.",
            "Un scientifique dans son laboratoire n'est pas seulement un technicien : c'est aussi un enfant placé en face de phénomènes naturels qui l'impressionnent comme des contes de fées.",
            "La science n'a pas de patrie, parce que le savoir est le patrimoine de l'humanité.",
            "Paris est toujours une bonne idée.",
            "Si vous avez la chance d'avoir vécu à Paris jeune, alors où que vous alliez pour le reste de votre vie, cela ne vous quitte pas, car Paris est une fête.",
            "À Paris, la beauté est à chaque coin de rue.",
            "L'amour commence par soi-même.",
            "Vivre sans aimer n'est pas proprement vivre.",
            "La parole est d'argent, mais le silence est d'or.",
            "On n'est jamais si heureux ni si malheureux qu'on se l'imagine.",
            "L'amour-propre est le plus grand de tous les flatteurs.",
            "Si l'on n'avait point de défauts, on ne prendrait pas tant de plaisir à en remarquer dans les autres.",
            "Le rire est la distance la plus courte entre deux personnes.",
            "L'avenir appartient à ceux qui préparent aujourd'hui.",
            "Rien ne sert de courir ; il faut partir à point.",
            "La raison du plus fort est toujours la meilleure.",
            "En toute chose il faut considérer la fin.",
            "La vie n'est pas un problème à résoudre, mais une réalité à expérimenter.",
            "Aime la vie et la vie t'aimera.",
            "Main character",
            "C'est un PN",
            "Red flag",
            "Green flag",
            "C'est un NPC",
            "Masterclass",
            "Ratio",
            "Les bails",
            "C'est quoi les bails ?",
            "Pick me",
            "Rentre dans le moule",
            "C'est du propre",
            "Vibe check",
            "Flex",
            "Soft launch",
            "Hard launch",
            "C'est un banger",
            "Flop",
            "Un flop monumentale",
            "C'est cringe",
            "Le cringe absolu",
            "Gatekeep",
            "Glow up",
            "Bro-code",
            "Sisterhood",
            "Drama",
            "Chercher le drama",
            "Vendre du rêve",
            "C'est la Hess",
            "C'est un GoAT",
            "No cap",
            "It boy / It girl",
            "Shitpost",
            "Mood du jour",
            "Pov",
            "Out of context",
            "Zero effort",
            "C'est valide",
            "In Real Life",
            "Based",
            "Mdr",
            "Ptdr",
            "Xptdr",
            "Jpp",
            "Stp",
            "Svp",
            "Tqt",
            "Slt",
            "Bjr",
            "Bsr",
            "Cc",
            "Mrc",
            "C'est dr",
            "Tkt mêm pas",
            "Jsp",
            "Jtnf",
            "Cmt",
            "Pq",
            "Pck",
            "Cad",
            "Bcp",
            "Tkt frérot",
            "Amdt",
            "Att",
            "Jtm",
            "Mdrrr",
            "A2m",
            "A+",
            "Aaf",
            "Tmtc",
            "Aussi",
            "Jpp de toi",
            "Thx",
            "Nsp",
            "Ghoster",
            "Stalker",
            "Breadcrumbing",
            "Benching",
            "Gaslighter",
            "Friendzone",
            "Un Crush",
            "Un BAE",
            "Un simpeur",
            "Simper",
            "Un DM",
            "Slide dans les DMs",
            "Un match",
            "Un superlike",
            "Un date",
            "Passer au vert",
            "Liker à mort",
            "La Story privée",
            "Faire un flop amoureux",
            "Demander un Insta",
            "Un faux compte",
            "Supprimer la convo",
            "Bloquer direct",
            "Un fan account",
            "Déswiper",
            "Être pris",
            "Être célibat",
            "Casser le game",
            "Faire le beau",
            "Grave amoureux",
            "Attrapper une veste",
            "Laisse tomber",
            "C'est mort",
            "Un faux ami",
            "Changer de disques",
            "T'es trop chou",
            "C'est une pépite",
            "C'est du grand art",
            "Je suis cuit",
            "Je suis par terre",
            "Je décède",
            "Je suis au sol",
            "Trop de scroll",
            "Inonder le fil",
            "C'est pas sorcier",
            "Un pnj total",
            "Trop de bluff",
            "Faire sa star",
            "Sans vergogne",
            "C'est la base",
            "Niveau zéro",
            "Un monstre",
            "T'es un champion",
            "C'est bon là",
            "Arrête tes salades",
            "T'abuse de fou",
            "C'est du lourd",
            "Totalement faux",
            "Trop de sauce",
            "Mettre la sauce",
            "C'est du génie",
            "J'ai pas la réf",
            "J'ai la réf",
            "Donne la réf",
            "Poteau sponsorisé",
            "Un placement de produit",
            "C'est du pipo",
            "Tu me fatigues",
            "C'est tendu",
            "Garde ton calme",
            "Un algorithme d'enfer",
            "Passer en TT",
            "Percer sur TikTok",
            "Faire des vues",
            "Un piège à clics",
            "C'est viral",
            "Mood",
            "Vibe",
            "Au bout de ma vie",
            "J'ai trop le seum",
            "Flemme olympique",
            "En dépression totale",
            "Mode fantôme",
            "Zero pression",
            "C'est chill",
            "Full énergie",
            "En galère",
            "C'est la crise",
            "Pas le temps de niaiser",
            "All-in",
            "En roue libre",
            "Sans prise de tête",
            "Ça me saoule",
            "Je craque",
            "J'en ai marre",
            "C'est insupportable",
            "Je pète les plombs",
            "J'suis choque de ouf",
            "Grave pas chaud",
            "Je démissionne",
            "Mode guerrier",
            "C'est gratifiant",
            "C'est du bonus",
            "On valide à 100%",
            "Faire dodo",
            "Prendre l'air",
            "Tranquille Émile",
            "Ça fait plaisir",
            "On se tiend au jus",
    };

    public SemanticMatcherFr(Context context) {
        super(context, TAG, ASSET_PATH, FALLBACK_QUESTIONS, randomActions());
    }

    /** fallback 動作全部 __RANDOM__：幾多答句就幾多個位，SemanticCenter
     *  見到呢個標記會即場隨機選動作 (見 ActionDirect.resolveRandomActionId())。 */
    private static String[] randomActions() {
        String[] a = new String[FALLBACK_QUESTIONS.length];
        for (int i = 0; i < a.length; i++) {
            a[i] = "__RANDOM__";
        }
        return a;
    }
}
