#!/usr/bin/env python3
"""
Generate typed JS ApiClient from openapi/open-alpha2-openapi.yml.

Usage:
  python scripts/generate-api-client.py
  -> writes app/src/main/assets/web/api-client.js

This is the "2. 前端 Typed JS" part of the 1+2 OpenAPI simplification:
- Single source of truth: openapi yaml
- No hand-written fetch("...alpha2/...") strings scattered across 8 app-*.js files
- Auto-validates enums/ranges before network round-trip (mirrors ApiValidator.java)
"""
import pathlib
import re
import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
SPEC = ROOT / "openapi" / "open-alpha2-openapi.yml"
OUT = ROOT / "app" / "src" / "main" / "assets" / "web" / "api-client.js"

def js_value(v):
    # enum 值轉 JS 字面值。YAML 1.1 地雷：off/on/yes/no 唔加引號會 parse 做
    # boolean，直接 f-string 會漏出 Python 字面值（False/True/None）整壞 JS。
    if v is True: return "true"
    if v is False: return "false"
    if v is None: return "null"
    return repr(v)

def to_camel(path: str) -> str:
    # /api/servo/one -> servoOne, /api/speech/tts_engines -> speechTtsEngines
    # strip /api/ and /api/system/ and /api/xiaozhi/ prefixes for brevity but keep namespace
    p = path
    for prefix in ["/api/system/", "/api/xiaozhi/", "/api/", "/upload/", "/stream/", "/"]:
        if p.startswith(prefix):
            p = p[len(prefix):]
            break
    # special cases
    if p in ("", "ws"): return p or "root"
    parts = re.split(r'[/_-]', p)
    camel = parts[0].lower() + ''.join(x.capitalize() for x in parts[1:])
    # make valid JS identifier
    camel = re.sub(r'[^a-zA-Z0-9]', '', camel)
    if not camel:
        camel = "api"
    return camel

def func_name(method: str, path: str) -> str:
    base = to_camel(path)
    # prefix with namespace to avoid collisions: system/music/list -> systemMusicList
    if path.startswith("/api/system/"):
        base = "system" + base[0].upper() + base[1:]
    elif path.startswith("/api/xiaozhi/"):
        base = "xiaozhi" + base[0].upper() + base[1:]
    elif path.startswith("/upload/"):
        base = "upload" + base[0].upper() + base[1:]
    elif path.startswith("/stream/"):
        base = "stream" + base[0].upper() + base[1:]
    # method hint for POST
    if method == "post" and not base.startswith("upload"):
        # keep as is, caller knows it's POST
        pass
    return base

SPECIFIC_DOC = {
    "/api/status": "取得系統狀態",
    "/api/servo/one": "單顆舵機",
    "/api/speech/tts": "TTS 播報",
}

with open(SPEC, encoding="utf-8") as f:
    spec = yaml.safe_load(f)

paths = spec.get("paths", {})

# Build JS
lines = []
lines.append("// auto-generated by scripts/generate-api-client.py — DO NOT EDIT MANUALLY")
lines.append("// source: openapi/open-alpha2-openapi.yml")
lines.append("// regenerate: python scripts/generate-api-client.py")
lines.append("")
lines.append("// Depends on the namespaced fetch helpers (fetch wrappers with error banner):")
lines.append("// api() (app-core.js/blockly-page.js), sysApi()/directApi() (ditto),")
lines.append("// xiaozhiApi() (app-xiaozhi.js/blockly-page.js), hwApi() (alias of api()).")
lines.append("// Provides typed wrappers with local enum/range validation before fetch,")
lines.append("// mirroring ApiValidator.java on the server side.")
lines.append("")
lines.append("const Alpha2Api = (function() {")
lines.append("  function qs(params) { return params ? '?' + new URLSearchParams(params).toString() : ''; }")
lines.append("  function assertEnum(val, allowed, key) { if (val != null && !allowed.includes(val)) throw new Error(key + ' must be one of ' + allowed.join(',')); }")
lines.append("  function assertRange(val, min, max, key) { if (val < min || val > max) throw new Error(key + ' must be between '+min+' and '+max); }")
lines.append("")

# Group by tag for readability
from collections import defaultdict
grouped = defaultdict(list)
for path, ops in paths.items():
    for method, op in ops.items():
        if method not in ("get","post","put","delete","patch"): continue
        tags = op.get("tags", ["core"])
        tag = tags[0]
        grouped[tag].append((path, method, op))

def resolve_params(params, spec):
    out=[]
    for p in params:
        if "$ref" in p:
            ref=p["$ref"]
            # e.g. #/components/parameters/TimeoutMs
            parts=ref.lstrip("#/").split("/")
            cur=spec
            for part in parts:
                cur=cur[part]
            out.append(cur)
        else:
            out.append(p)
    return out

for tag in sorted(grouped.keys()):
    lines.append(f"  // ── {tag} ──────────────────────────────────────────────")
    for path, method, op in sorted(grouped[tag]):
        summary = op.get("summary","").replace('"','\\"').replace("\n"," ")
        # build param list from spec
        params = resolve_params(op.get("parameters", []), spec)
        # also consider requestBody? skip for GET
        param_names = [str(p["name"]) for p in params]
        # create function signature: takes an object {param: value}
        # for no-param endpoints, no arg
        fid = func_name(method, path)
        # avoid duplicate names: if duplicate, append method
        # collect already seen
        # Build JS doc
        js_params = []
        for p in params:
            name = str(p["name"])
            req = p.get("required", False)
            typ = p.get("schema",{}).get("type","string")
            js_params.append(f"{name}{'!' if req else ''}:{typ}")
        doc = f"{fid}({', '.join(param_names)}) — {summary} [{method.upper()} {path}]"
        # /upload/*, /stream/*, /ws, /, /blockly.html 有各自 handler，不經 JSON api
        if path.startswith("/upload/") or path.startswith("/stream/") or path == "/ws":
            # skip generating for non-API (stream/ws/upload) — they have separate handlers
            continue
        if path in ("/", "/blockly.html"):
            continue
        # Caller 必須同後端路由前綴對齊 (見 MainActivity dispatch + check-api-client-routes.py)：
        # api() -> /api/alpha2/* (handleApi), sysApi() -> /api/system/*,
        # directApi() -> /api/direct/*, xiaozhiApi() -> /api/xiaozhi/*。
        # 直接用 api('system/...') 會打去 /api/alpha2/system/... 而 404。
        if path.startswith("/api/system/"):
            caller, rel = "sysApi", path[len("/api/system/"):]
        elif path.startswith("/api/direct/"):
            caller, rel = "directApi", path[len("/api/direct/"):]
        elif path.startswith("/api/xiaozhi/"):
            caller, rel = "xiaozhiApi", path[len("/api/xiaozhi/"):]
        elif path.startswith("/api/"):
            caller, rel = "api", path[len("/api/"):]
        else:
            continue

        # Generate function
        # For simplicity, all functions take a single `params` object, matching URLSearchParams usage in app-core.js
        # e.g. Alpha2Api.servoOne({id:1, angle:90, time:1000})
        lines.append(f"  function {fid}(params) {{")
        # Add enum/range asserts based on spec parameters
        for p in params:
            name = str(p["name"])
            schema = p.get("schema", {})
            enum_vals = schema.get("enum")
            if enum_vals:
                js_list = "[" + ", ".join(js_value(v) for v in enum_vals) + "]"
                lines.append(f"    if (params && params.{name} != null) assertEnum(params.{name}, {js_list}, '{name}');")
            if schema.get("type") == "integer" and ("minimum" in schema or "maximum" in schema):
                mn = schema.get("minimum", -1e9)
                mx = schema.get("maximum", 1e9)
                # only if both present, else just range check
                if "minimum" in schema and "maximum" in schema:
                    lines.append(f"    if (params && params.{name} != null) assertRange(Number(params.{name}), {mn}, {mx}, '{name}');")
        # Build call
        # Determine if method is GET or POST: the fetch helpers always do GET via fetch(API+prefix+path+qs)
        # For POST endpoints (e.g. /api/chest/upgrade, /api/alice/talkServer), we still use GET in current impl.
        # We note that spec says POST but current server accepts GET as well (handlers don't check method). So we keep GET.
        lines.append(f"    // {summary}")
        lines.append(f"    return {caller}('{rel}', params);")
        lines.append(f"  }}")
        lines.append("")

# Add hwApi aliases for legacy name compatibility
lines.append("  // ── legacy aliases (hwApi) ─────────────────────────────")
lines.append("  function hw(path, params) { return hwApi(path, params); }")
lines.append("")

# Export object
lines.append("  return {")
# collect function names
exported = []
for tag in sorted(grouped.keys()):
    for path, method, op in sorted(grouped[tag]):
        if path.startswith("/upload/") or path.startswith("/stream/") or path in ("/","/blockly.html","/ws"): continue
        if not path.startswith("/api/"): continue
        fid = func_name(method, path)
        # deduplicate
        if fid not in exported:
            exported.append(fid)
            lines.append(f"    {fid},")
lines.append("    hw,")
lines.append("  };")
lines.append("})();")
lines.append("")
lines.append("// Usage examples:")
lines.append("//   Alpha2Api.status()")
lines.append("//   Alpha2Api.servoOne({id:1, angle:90, time:1000})")
lines.append("//   Alpha2Api.speechTts({text:'你好', engine:'android'})")
lines.append("//   Alpha2Api.ledHeadSet({color:1, brightness:9, preset:'breathe'})")
lines.append("//   Alpha2Api.xiaozhiConnect()")

OUT.parent.mkdir(parents=True, exist_ok=True)
# 強制使用 LF 換行，否則 Windows 上 pathlib 預設會轉為 CRLF，導致 CI (Ubuntu/LF) 的 git diff 誤判 drift。
# 參考 logs_91129359938.zip drift 失敗：整個 api-client.js 被視為 758 行全改，實為 CRLF vs LF + 缺尾換行。
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print(f"Wrote {OUT} with {len(exported)} functions")
